/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.tax;

// Generated Sep 4, 2008 8:23:32 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * GeoZonesTaxTemplate generated by hbm2java
 */
public class GeoZoneTaxTemplate implements java.io.Serializable {

	// Fields

	private long geoZoneId;

	private String geoZoneName;

	private String geoZoneDescription;

	private Date lastModified;

	private Date dateAdded;

	private int schemeid;

	// Constructors

	/** default constructor */
	public GeoZoneTaxTemplate() {
	}

	/** minimal constructor */
	public GeoZoneTaxTemplate(long geoZoneId, String geoZoneName,
			String geoZoneDescription, Date dateAdded, int schemeid) {
		this.geoZoneId = geoZoneId;
		this.geoZoneName = geoZoneName;
		this.geoZoneDescription = geoZoneDescription;
		this.dateAdded = dateAdded;
		this.schemeid = schemeid;
	}

	/** full constructor */
	public GeoZoneTaxTemplate(long geoZoneId, String geoZoneName,
			String geoZoneDescription, Date lastModified, Date dateAdded,
			int schemeid) {
		this.geoZoneId = geoZoneId;
		this.geoZoneName = geoZoneName;
		this.geoZoneDescription = geoZoneDescription;
		this.lastModified = lastModified;
		this.dateAdded = dateAdded;
		this.schemeid = schemeid;
	}

	// Property accessors
	public long getGeoZoneId() {
		return this.geoZoneId;
	}

	public void setGeoZoneId(long geoZoneId) {
		this.geoZoneId = geoZoneId;
	}

	public String getGeoZoneName() {
		return this.geoZoneName;
	}

	public void setGeoZoneName(String geoZoneName) {
		this.geoZoneName = geoZoneName;
	}

	public String getGeoZoneDescription() {
		return this.geoZoneDescription;
	}

	public void setGeoZoneDescription(String geoZoneDescription) {
		this.geoZoneDescription = geoZoneDescription;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public int getSchemeid() {
		return this.schemeid;
	}

	public void setSchemeid(int schemeid) {
		this.schemeid = schemeid;
	}

}
