/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.tax;

// Generated Sep 4, 2008 8:23:32 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

/**
 * TaxRatesTaxTemplate generated by hbm2java
 */
public class TaxRateTaxTemplate implements java.io.Serializable {

	// Fields

	private long taxRateId;

	private long taxZoneId;

	private long taxClassId;

	private Integer taxPriority;

	private BigDecimal taxRate;

	private Date lastModified;

	private Date dateAdded;

	private boolean piggyback;

	private ZoneToGeoZoneTaxTemplate zoneToGeoZone;

	private Set<TaxRateDescriptionTaxTemplate> descriptions;

	// Constructors

	public Set<TaxRateDescriptionTaxTemplate> getDescriptions() {
		return descriptions;
	}

	public void setDescriptions(Set<TaxRateDescriptionTaxTemplate> descriptions) {
		this.descriptions = descriptions;
	}

	public ZoneToGeoZoneTaxTemplate getZoneToGeoZone() {
		return zoneToGeoZone;
	}

	public void setZoneToGeoZone(ZoneToGeoZoneTaxTemplate zoneToGeoZone) {
		this.zoneToGeoZone = zoneToGeoZone;
	}

	/** default constructor */
	public TaxRateTaxTemplate() {
	}

	/** minimal constructor */
	public TaxRateTaxTemplate(long taxRateId, long taxZoneId, long taxClassId,
			BigDecimal taxRate, Date dateAdded) {
		this.taxRateId = taxRateId;
		this.taxZoneId = taxZoneId;
		this.taxClassId = taxClassId;
		this.taxRate = taxRate;
		this.dateAdded = dateAdded;
	}

	/** full constructor */
	public TaxRateTaxTemplate(long taxRateId, long taxZoneId, long taxClassId,
			Integer taxPriority, BigDecimal taxRate, Date lastModified,
			Date dateAdded) {
		this.taxRateId = taxRateId;
		this.taxZoneId = taxZoneId;
		this.taxClassId = taxClassId;
		this.taxPriority = taxPriority;
		this.taxRate = taxRate;
		this.lastModified = lastModified;
		this.dateAdded = dateAdded;
	}

	// Property accessors
	public long getTaxRateId() {
		return this.taxRateId;
	}

	public void setTaxRateId(long taxRateId) {
		this.taxRateId = taxRateId;
	}

	public long getTaxZoneId() {
		return this.taxZoneId;
	}

	public void setTaxZoneId(long taxZoneId) {
		this.taxZoneId = taxZoneId;
	}

	public long getTaxClassId() {
		return this.taxClassId;
	}

	public void setTaxClassId(long taxClassId) {
		this.taxClassId = taxClassId;
	}

	public Integer getTaxPriority() {
		return this.taxPriority;
	}

	public void setTaxPriority(Integer taxPriority) {
		this.taxPriority = taxPriority;
	}

	public BigDecimal getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(BigDecimal taxRate) {
		this.taxRate = taxRate;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public boolean isPiggyback() {
		return piggyback;
	}

	public void setPiggyback(boolean piggyback) {
		this.piggyback = piggyback;
	}

}
