/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.tax;

// Generated Sep 4, 2008 8:23:32 PM by Hibernate Tools 3.2.0.beta8

/**
 * TaxRatesDescription generated by hbm2java
 */
public class TaxRateDescription implements java.io.Serializable {

	// Fields

	private TaxRateDescriptionId id;

	private String taxDescription;

	// Constructors

	/** default constructor */
	public TaxRateDescription() {
	}

	/** full constructor */
	public TaxRateDescription(TaxRateDescriptionId id, String taxDescription) {
		this.id = id;
		this.taxDescription = taxDescription;
	}

	// Property accessors
	public TaxRateDescriptionId getId() {
		return this.id;
	}

	public void setId(TaxRateDescriptionId id) {
		this.id = id;
	}

	public String getTaxDescription() {
		return this.taxDescription;
	}

	public void setTaxDescription(String taxDescription) {
		this.taxDescription = taxDescription;
	}

	@Override
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((id == null) ? 0 : id.hashCode());
		result = PRIME * result
				+ ((taxDescription == null) ? 0 : taxDescription.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final TaxRateDescription other = (TaxRateDescription) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (taxDescription == null) {
			if (other.taxDescription != null)
				return false;
		} else if (!taxDescription.equals(other.taxDescription))
			return false;
		return true;
	}

}
