/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.tax;

// Generated Sep 4, 2008 8:23:32 PM by Hibernate Tools 3.2.0.beta8

/**
 * TaxRatesDescriptionTaxTemplate generated by hbm2java
 */
public class TaxRateDescriptionTaxTemplate implements java.io.Serializable {

	// Fields

	private TaxRateDescriptionTaxTemplateId id;

	private String taxDescription;

	// Constructors

	/** default constructor */
	public TaxRateDescriptionTaxTemplate() {
	}

	/** full constructor */
	public TaxRateDescriptionTaxTemplate(TaxRateDescriptionTaxTemplateId id,
			String taxDescription) {
		this.id = id;
		this.taxDescription = taxDescription;
	}

	// Property accessors
	public TaxRateDescriptionTaxTemplateId getId() {
		return this.id;
	}

	public void setId(TaxRateDescriptionTaxTemplateId id) {
		this.id = id;
	}

	public String getTaxDescription() {
		return this.taxDescription;
	}

	public void setTaxDescription(String taxDescription) {
		this.taxDescription = taxDescription;
	}

}
