/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.orders;

// Generated Apr 3, 2009 8:19:31 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * OrdersAccountProducts generated by hbm2java
 */
public class OrderAccountProduct implements java.io.Serializable {

	// Fields

	private long orderAccountProductId;

	private long orderAccountId;

	private long orderProductId;

	private Date orderAccountProductStartDate;

	private Date orderAccountProductEndDate;

	private Date orderAccountProductEot;

	private Date orderAccountProductAccountedDate;

	private Date orderAccountProductLastStatusDate;

	private int orderAccountProductLastTransactionStatus;

	private int orderAccountProductPaymentFrequencyType;

	private int orderAccountProductStatus;

	// Constructors

	/** default constructor */
	public OrderAccountProduct() {
	}

	/** minimal constructor */
	public OrderAccountProduct(long orderAccountProductId, long orderAccountId,
			long orderProductId, Date orderAccountProductStartDate,
			int orderAccountProductLastTransactionStatus,
			int orderAccountProductPaymentFrequencyType,
			int orderAccountProductStatus) {
		this.orderAccountProductId = orderAccountProductId;
		this.orderAccountId = orderAccountId;
		this.orderProductId = orderProductId;
		this.orderAccountProductStartDate = orderAccountProductStartDate;
		this.orderAccountProductLastTransactionStatus = orderAccountProductLastTransactionStatus;
		this.orderAccountProductPaymentFrequencyType = orderAccountProductPaymentFrequencyType;
		this.orderAccountProductStatus = orderAccountProductStatus;
	}

	/** full constructor */
	public OrderAccountProduct(long orderAccountProductId, long orderAccountId,
			long orderProductId, Date orderAccountProductStartDate,
			Date orderAccountProductEndDate, Date orderAccountProductEot,
			Date orderAccountProductAccountedDate,
			Date orderAccountProductLastStatusDate,
			int orderAccountProductLastTransactionStatus,
			int orderAccountProductPaymentFrequencyType,
			int orderAccountProductStatus) {
		this.orderAccountProductId = orderAccountProductId;
		this.orderAccountId = orderAccountId;
		this.orderProductId = orderProductId;
		this.orderAccountProductStartDate = orderAccountProductStartDate;
		this.orderAccountProductEndDate = orderAccountProductEndDate;
		this.orderAccountProductEot = orderAccountProductEot;
		this.orderAccountProductAccountedDate = orderAccountProductAccountedDate;
		this.orderAccountProductLastStatusDate = orderAccountProductLastStatusDate;
		this.orderAccountProductLastTransactionStatus = orderAccountProductLastTransactionStatus;
		this.orderAccountProductPaymentFrequencyType = orderAccountProductPaymentFrequencyType;
		this.orderAccountProductStatus = orderAccountProductStatus;
	}

	// Property accessors
	public long getOrderAccountProductId() {
		return this.orderAccountProductId;
	}

	public void setOrderAccountProductId(long orderAccountProductId) {
		this.orderAccountProductId = orderAccountProductId;
	}

	public long getOrderAccountId() {
		return this.orderAccountId;
	}

	public void setOrderAccountId(long orderAccountId) {
		this.orderAccountId = orderAccountId;
	}

	public long getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(long orderProductId) {
		this.orderProductId = orderProductId;
	}

	public Date getOrderAccountProductStartDate() {
		return this.orderAccountProductStartDate;
	}

	public void setOrderAccountProductStartDate(
			Date orderAccountProductStartDate) {
		this.orderAccountProductStartDate = orderAccountProductStartDate;
	}

	public Date getOrderAccountProductEndDate() {
		return this.orderAccountProductEndDate;
	}

	public void setOrderAccountProductEndDate(Date orderAccountProductEndDate) {
		this.orderAccountProductEndDate = orderAccountProductEndDate;
	}

	public Date getOrderAccountProductEot() {
		return this.orderAccountProductEot;
	}

	public void setOrderAccountProductEot(Date orderAccountProductEot) {
		this.orderAccountProductEot = orderAccountProductEot;
	}

	public Date getOrderAccountProductAccountedDate() {
		return this.orderAccountProductAccountedDate;
	}

	public void setOrderAccountProductAccountedDate(
			Date orderAccountProductAccountedDate) {
		this.orderAccountProductAccountedDate = orderAccountProductAccountedDate;
	}

	public Date getOrderAccountProductLastStatusDate() {
		return this.orderAccountProductLastStatusDate;
	}

	public void setOrderAccountProductLastStatusDate(
			Date orderAccountProductLastStatusDate) {
		this.orderAccountProductLastStatusDate = orderAccountProductLastStatusDate;
	}

	public int getOrderAccountProductLastTransactionStatus() {
		return this.orderAccountProductLastTransactionStatus;
	}

	public void setOrderAccountProductLastTransactionStatus(
			int orderAccountProductLastTransactionStatus) {
		this.orderAccountProductLastTransactionStatus = orderAccountProductLastTransactionStatus;
	}

	public int getOrderAccountProductPaymentFrequencyType() {
		return this.orderAccountProductPaymentFrequencyType;
	}

	public void setOrderAccountProductPaymentFrequencyType(
			int orderAccountProductPaymentFrequencyType) {
		this.orderAccountProductPaymentFrequencyType = orderAccountProductPaymentFrequencyType;
	}

	public int getOrderAccountProductStatus() {
		return this.orderAccountProductStatus;
	}

	public void setOrderAccountProductStatus(int orderAccountProductStatus) {
		this.orderAccountProductStatus = orderAccountProductStatus;
	}

}
