/*
 * Provided by CSTI Consulting 
 * Following GNU LESSER GENERAL PUBLIC LICENSE
 * You may obtain more details at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.central.entity.functions;

// Generated Aug 13, 2007 10:04:04 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * CentralGroupRegistration generated by hbm2java
 */
public class CentralGroupRegistration implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3860784908926537285L;
	private int centralRegistrationAssociationId;
	private int merchantRegistrationDefCode;
	private String centralGroupCode;
	private boolean centralGroupVisible;
	private byte centralGroupPosition;
	private int promotionCode;
	private String centralGroupDescription;
	private boolean centralGroupNew;
	private Date centralGroupNewUntil;

	public CentralGroupRegistration() {
	}

	public CentralGroupRegistration(int centralRegistrationAssociationId,
			int merchantRegistrationDefCode, String centralGroupCode,
			boolean centralGroupVisible, byte centralGroupPosition,
			int promotionCode, boolean centralGroupNew) {
		this.centralRegistrationAssociationId = centralRegistrationAssociationId;
		this.merchantRegistrationDefCode = merchantRegistrationDefCode;
		this.centralGroupCode = centralGroupCode;
		this.centralGroupVisible = centralGroupVisible;
		this.centralGroupPosition = centralGroupPosition;
		this.promotionCode = promotionCode;
		this.centralGroupNew = centralGroupNew;
	}

	public CentralGroupRegistration(int centralRegistrationAssociationId,
			int merchantRegistrationDefCode, String centralGroupCode,
			boolean centralGroupVisible, byte centralGroupPosition,
			int promotionCode, String centralGroupDescription,
			boolean centralGroupNew, Date centralGroupNewUntil) {
		this.centralRegistrationAssociationId = centralRegistrationAssociationId;
		this.merchantRegistrationDefCode = merchantRegistrationDefCode;
		this.centralGroupCode = centralGroupCode;
		this.centralGroupVisible = centralGroupVisible;
		this.centralGroupPosition = centralGroupPosition;
		this.promotionCode = promotionCode;
		this.centralGroupDescription = centralGroupDescription;
		this.centralGroupNew = centralGroupNew;
		this.centralGroupNewUntil = centralGroupNewUntil;
	}

	public int getCentralRegistrationAssociationId() {
		return this.centralRegistrationAssociationId;
	}

	public void setCentralRegistrationAssociationId(
			int centralRegistrationAssociationId) {
		this.centralRegistrationAssociationId = centralRegistrationAssociationId;
	}

	public int getMerchantRegistrationDefCode() {
		return this.merchantRegistrationDefCode;
	}

	public void setMerchantRegistrationDefCode(int merchantRegistrationDefCode) {
		this.merchantRegistrationDefCode = merchantRegistrationDefCode;
	}

	public String getCentralGroupCode() {
		return this.centralGroupCode;
	}

	public void setCentralGroupCode(String centralGroupCode) {
		this.centralGroupCode = centralGroupCode;
	}

	public boolean isCentralGroupVisible() {
		return this.centralGroupVisible;
	}

	public void setCentralGroupVisible(boolean centralGroupVisible) {
		this.centralGroupVisible = centralGroupVisible;
	}

	public byte getCentralGroupPosition() {
		return this.centralGroupPosition;
	}

	public void setCentralGroupPosition(byte centralGroupPosition) {
		this.centralGroupPosition = centralGroupPosition;
	}

	public int getPromotionCode() {
		return this.promotionCode;
	}

	public void setPromotionCode(int promotionCode) {
		this.promotionCode = promotionCode;
	}

	public String getCentralGroupDescription() {
		return this.centralGroupDescription;
	}

	public void setCentralGroupDescription(String centralGroupDescription) {
		this.centralGroupDescription = centralGroupDescription;
	}

	public boolean isCentralGroupNew() {
		return this.centralGroupNew;
	}

	public void setCentralGroupNew(boolean centralGroupNew) {
		this.centralGroupNew = centralGroupNew;
	}

	public Date getCentralGroupNewUntil() {
		return this.centralGroupNewUntil;
	}

	public void setCentralGroupNewUntil(Date centralGroupNewUntil) {
		this.centralGroupNewUntil = centralGroupNewUntil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CentralGroupRegistration))
			return false;
		CentralGroupRegistration castOther = (CentralGroupRegistration) other;

		return (this.getCentralRegistrationAssociationId() == castOther
				.getCentralRegistrationAssociationId())
				&& (this.getMerchantRegistrationDefCode() == castOther
						.getMerchantRegistrationDefCode())
				&& ((this.getCentralGroupCode() == castOther
						.getCentralGroupCode()) || (this.getCentralGroupCode() != null
						&& castOther.getCentralGroupCode() != null && this
						.getCentralGroupCode().equals(
								castOther.getCentralGroupCode())))
				&& (this.isCentralGroupVisible() == castOther
						.isCentralGroupVisible())
				&& (this.getCentralGroupPosition() == castOther
						.getCentralGroupPosition())
				&& (this.getPromotionCode() == castOther.getPromotionCode())
				&& ((this.getCentralGroupDescription() == castOther
						.getCentralGroupDescription()) || (this
						.getCentralGroupDescription() != null
						&& castOther.getCentralGroupDescription() != null && this
						.getCentralGroupDescription().equals(
								castOther.getCentralGroupDescription())))
				&& (this.isCentralGroupNew() == castOther.isCentralGroupNew())
				&& ((this.getCentralGroupNewUntil() == castOther
						.getCentralGroupNewUntil()) || (this
						.getCentralGroupNewUntil() != null
						&& castOther.getCentralGroupNewUntil() != null && this
						.getCentralGroupNewUntil().equals(
								castOther.getCentralGroupNewUntil())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCentralRegistrationAssociationId();
		result = 37 * result + this.getMerchantRegistrationDefCode();
		result = 37
				* result
				+ (getCentralGroupCode() == null ? 0 : this
						.getCentralGroupCode().hashCode());
		result = 37 * result + (this.isCentralGroupVisible() ? 1 : 0);
		result = 37 * result + this.getCentralGroupPosition();
		result = 37 * result + this.getPromotionCode();
		result = 37
				* result
				+ (getCentralGroupDescription() == null ? 0 : this
						.getCentralGroupDescription().hashCode());
		result = 37 * result + (this.isCentralGroupNew() ? 1 : 0);
		result = 37
				* result
				+ (getCentralGroupNewUntil() == null ? 0 : this
						.getCentralGroupNewUntil().hashCode());
		return result;
	}

}
