/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.payment;

// Generated Oct 1, 2008 9:31:43 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * MerchantPaymentGatewayTrx generated by hbm2java
 */
public class MerchantPaymentGatewayTrx implements java.io.Serializable {

	// Fields

	private long merchantPaymentGwId;

	private int merchantId;

	private long customerid;

	private long orderId;

	private String merchantPaymentGwMethod;

	private String merchantPaymentGwOrderid;

	private String merchantPaymentGwRespcode;

	private String merchantPaymentGwTrxid;

	private String merchantPaymentGwAuthtype;

	private String merchantPaymentGwSent;

	private String merchantPaymentGwReceived;

	private String merchantPaymentGwSession;

	private Date dateAdded;

	private String gatewaySentDecrypted;// transient

	private java.math.BigDecimal amount;

	// Constructors

	public MerchantPaymentGatewayTrx(long merchantPaymentGwId, int merchantId,
			long customerid, long orderId, String merchantPaymentGwMethod,
			String merchantPaymentGwOrderid, String merchantPaymentGwRespcode,
			String merchantPaymentGwTrxid, String merchantPaymentGwAuthtype,
			String merchantPaymentGwSent, String merchantPaymentGwReceived,
			String merchantPaymentGwSession, Date dateAdded,
			java.math.BigDecimal amount) {
		super();
		this.merchantPaymentGwId = merchantPaymentGwId;
		this.merchantId = merchantId;
		this.customerid = customerid;
		this.orderId = orderId;
		this.merchantPaymentGwMethod = merchantPaymentGwMethod;
		this.merchantPaymentGwOrderid = merchantPaymentGwOrderid;
		this.merchantPaymentGwRespcode = merchantPaymentGwRespcode;
		this.merchantPaymentGwTrxid = merchantPaymentGwTrxid;
		this.merchantPaymentGwAuthtype = merchantPaymentGwAuthtype;
		this.merchantPaymentGwSent = merchantPaymentGwSent;
		this.merchantPaymentGwReceived = merchantPaymentGwReceived;
		this.merchantPaymentGwSession = merchantPaymentGwSession;
		this.dateAdded = dateAdded;
		this.amount = amount;
	}

	/** default constructor */
	public MerchantPaymentGatewayTrx() {
	}

	public long getCustomerid() {
		return customerid;
	}

	public void setCustomerid(long customerid) {
		this.customerid = customerid;
	}

	public Date getDateAdded() {
		return dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public int getMerchantId() {
		return merchantId;
	}

	public void setMerchantId(int merchantId) {
		this.merchantId = merchantId;
	}

	public String getMerchantPaymentGwAuthtype() {
		return merchantPaymentGwAuthtype;
	}

	public void setMerchantPaymentGwAuthtype(String merchantPaymentGwAuthtype) {
		this.merchantPaymentGwAuthtype = merchantPaymentGwAuthtype;
	}

	public long getMerchantPaymentGwId() {
		return merchantPaymentGwId;
	}

	public void setMerchantPaymentGwId(long merchantPaymentGwId) {
		this.merchantPaymentGwId = merchantPaymentGwId;
	}

	public String getMerchantPaymentGwMethod() {
		return merchantPaymentGwMethod;
	}

	public void setMerchantPaymentGwMethod(String merchantPaymentGwMethod) {
		this.merchantPaymentGwMethod = merchantPaymentGwMethod;
	}

	public String getMerchantPaymentGwOrderid() {
		return merchantPaymentGwOrderid;
	}

	public void setMerchantPaymentGwOrderid(String merchantPaymentGwOrderid) {
		this.merchantPaymentGwOrderid = merchantPaymentGwOrderid;
	}

	public String getMerchantPaymentGwReceived() {
		return merchantPaymentGwReceived;
	}

	public void setMerchantPaymentGwReceived(String merchantPaymentGwReceived) {
		this.merchantPaymentGwReceived = merchantPaymentGwReceived;
	}

	public String getMerchantPaymentGwRespcode() {
		return merchantPaymentGwRespcode;
	}

	public void setMerchantPaymentGwRespcode(String merchantPaymentGwRespcode) {
		this.merchantPaymentGwRespcode = merchantPaymentGwRespcode;
	}

	public String getMerchantPaymentGwSent() {
		return merchantPaymentGwSent;
	}

	public void setMerchantPaymentGwSent(String merchantPaymentGwSent) {
		this.merchantPaymentGwSent = merchantPaymentGwSent;
	}

	public String getMerchantPaymentGwSession() {
		return merchantPaymentGwSession;
	}

	public void setMerchantPaymentGwSession(String merchantPaymentGwSession) {
		this.merchantPaymentGwSession = merchantPaymentGwSession;
	}

	public String getMerchantPaymentGwTrxid() {
		return merchantPaymentGwTrxid;
	}

	public void setMerchantPaymentGwTrxid(String merchantPaymentGwTrxid) {
		this.merchantPaymentGwTrxid = merchantPaymentGwTrxid;
	}

	public long getOrderId() {
		return orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public java.math.BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(java.math.BigDecimal amount) {
		this.amount = amount;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((amount == null) ? 0 : amount.hashCode());
		result = prime * result + (int) (customerid ^ (customerid >>> 32));
		result = prime * result
				+ ((dateAdded == null) ? 0 : dateAdded.hashCode());
		result = prime * result + merchantId;
		result = prime
				* result
				+ ((merchantPaymentGwAuthtype == null) ? 0
						: merchantPaymentGwAuthtype.hashCode());
		result = prime * result
				+ (int) (merchantPaymentGwId ^ (merchantPaymentGwId >>> 32));
		result = prime
				* result
				+ ((merchantPaymentGwMethod == null) ? 0
						: merchantPaymentGwMethod.hashCode());
		result = prime
				* result
				+ ((merchantPaymentGwOrderid == null) ? 0
						: merchantPaymentGwOrderid.hashCode());
		result = prime
				* result
				+ ((merchantPaymentGwReceived == null) ? 0
						: merchantPaymentGwReceived.hashCode());
		result = prime
				* result
				+ ((merchantPaymentGwRespcode == null) ? 0
						: merchantPaymentGwRespcode.hashCode());
		result = prime
				* result
				+ ((merchantPaymentGwSent == null) ? 0 : merchantPaymentGwSent
						.hashCode());
		result = prime
				* result
				+ ((merchantPaymentGwSession == null) ? 0
						: merchantPaymentGwSession.hashCode());
		result = prime
				* result
				+ ((merchantPaymentGwTrxid == null) ? 0
						: merchantPaymentGwTrxid.hashCode());
		result = prime * result + (int) (orderId ^ (orderId >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MerchantPaymentGatewayTrx other = (MerchantPaymentGatewayTrx) obj;
		if (amount == null) {
			if (other.amount != null)
				return false;
		} else if (!amount.equals(other.amount))
			return false;
		if (customerid != other.customerid)
			return false;
		if (dateAdded == null) {
			if (other.dateAdded != null)
				return false;
		} else if (!dateAdded.equals(other.dateAdded))
			return false;
		if (merchantId != other.merchantId)
			return false;
		if (merchantPaymentGwAuthtype == null) {
			if (other.merchantPaymentGwAuthtype != null)
				return false;
		} else if (!merchantPaymentGwAuthtype
				.equals(other.merchantPaymentGwAuthtype))
			return false;
		if (merchantPaymentGwId != other.merchantPaymentGwId)
			return false;
		if (merchantPaymentGwMethod == null) {
			if (other.merchantPaymentGwMethod != null)
				return false;
		} else if (!merchantPaymentGwMethod
				.equals(other.merchantPaymentGwMethod))
			return false;
		if (merchantPaymentGwOrderid == null) {
			if (other.merchantPaymentGwOrderid != null)
				return false;
		} else if (!merchantPaymentGwOrderid
				.equals(other.merchantPaymentGwOrderid))
			return false;
		if (merchantPaymentGwReceived == null) {
			if (other.merchantPaymentGwReceived != null)
				return false;
		} else if (!merchantPaymentGwReceived
				.equals(other.merchantPaymentGwReceived))
			return false;
		if (merchantPaymentGwRespcode == null) {
			if (other.merchantPaymentGwRespcode != null)
				return false;
		} else if (!merchantPaymentGwRespcode
				.equals(other.merchantPaymentGwRespcode))
			return false;
		if (merchantPaymentGwSent == null) {
			if (other.merchantPaymentGwSent != null)
				return false;
		} else if (!merchantPaymentGwSent.equals(other.merchantPaymentGwSent))
			return false;
		if (merchantPaymentGwSession == null) {
			if (other.merchantPaymentGwSession != null)
				return false;
		} else if (!merchantPaymentGwSession
				.equals(other.merchantPaymentGwSession))
			return false;
		if (merchantPaymentGwTrxid == null) {
			if (other.merchantPaymentGwTrxid != null)
				return false;
		} else if (!merchantPaymentGwTrxid.equals(other.merchantPaymentGwTrxid))
			return false;
		if (orderId != other.orderId)
			return false;
		return true;
	}

	public String getGatewaySentDecrypted() {
		return gatewaySentDecrypted;
	}

	public void setGatewaySentDecrypted(String gatewaySentDecrypted) {
		this.gatewaySentDecrypted = gatewaySentDecrypted;
	}

}
