/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.payment;

// Generated Jun 14, 2009 10:25:44 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * OffsystemPendingOrders generated by hbm2java
 */
public class OffsystemPendingOrder implements java.io.Serializable {

	// Fields

	private long offsystemPendingOrderId;

	private Date dateAdded;

	private String payerEmail;

	private String transactionId;

	private long orderId;

	private String offsystemModule;

	private Integer merchantId;

	// Constructors

	/** default constructor */
	public OffsystemPendingOrder() {
	}

	/** minimal constructor */
	public OffsystemPendingOrder(long offsystemPendingOrderId, Date dateAdded,
			String payerEmail, String transactionId, long orderId,
			String offsystemModule) {
		this.offsystemPendingOrderId = offsystemPendingOrderId;
		this.dateAdded = dateAdded;
		this.payerEmail = payerEmail;
		this.transactionId = transactionId;
		this.orderId = orderId;
		this.offsystemModule = offsystemModule;
	}

	/** full constructor */
	public OffsystemPendingOrder(long offsystemPendingOrderId, Date dateAdded,
			String payerEmail, String transactionId, long orderId,
			String offsystemModule, Integer merchantId) {
		this.offsystemPendingOrderId = offsystemPendingOrderId;
		this.dateAdded = dateAdded;
		this.payerEmail = payerEmail;
		this.transactionId = transactionId;
		this.orderId = orderId;
		this.offsystemModule = offsystemModule;
		this.merchantId = merchantId;
	}

	// Property accessors
	public long getOffsystemPendingOrderId() {
		return this.offsystemPendingOrderId;
	}

	public void setOffsystemPendingOrderId(long offsystemPendingOrderId) {
		this.offsystemPendingOrderId = offsystemPendingOrderId;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public String getPayerEmail() {
		return this.payerEmail;
	}

	public void setPayerEmail(String payerEmail) {
		this.payerEmail = payerEmail;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public String getOffsystemModule() {
		return this.offsystemModule;
	}

	public void setOffsystemModule(String offsystemModule) {
		this.offsystemModule = offsystemModule;
	}

	public Integer getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(Integer merchantId) {
		this.merchantId = merchantId;
	}

}
