/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.payment;

// Generated Apr 10, 2009 10:47:05 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * OffsystemNotificationOrders generated by hbm2java
 */
public class OffsystemNotificationOrder implements java.io.Serializable {

	// Fields

	private long offsystemNotificationOrderId;
	private long offsystemPendingOrderId;

	private String payerEmail;

	private Date dateReceived;

	private String offsystemModule;

	private Integer merchantId;

	private Integer offsystemStatus;

	private String offsystemDetails;

	// Constructors

	/** default constructor */
	public OffsystemNotificationOrder() {
	}

	/** minimal constructor */
	public OffsystemNotificationOrder(long offsystemNotificationOrderId,
			long offsystemPendingOrderId, Date dateReceived,
			String offsystemModule, String payerEmail) {
		this.offsystemNotificationOrderId = offsystemNotificationOrderId;
		this.offsystemPendingOrderId = offsystemPendingOrderId;
		this.dateReceived = dateReceived;
		this.offsystemModule = offsystemModule;
		this.payerEmail = payerEmail;
	}

	/** full constructor */
	public OffsystemNotificationOrder(long offsystemNotificationOrderId,
			long offsystemPendingOrderId, Date dateReceived,
			String offsystemModule, Integer merchantId,
			Integer offsystemStatus, String offsystemDetails, String payerEmail) {
		this.offsystemNotificationOrderId = offsystemNotificationOrderId;
		this.offsystemPendingOrderId = offsystemPendingOrderId;
		this.dateReceived = dateReceived;
		this.offsystemModule = offsystemModule;
		this.merchantId = merchantId;
		this.offsystemStatus = offsystemStatus;
		this.offsystemDetails = offsystemDetails;
		this.payerEmail = payerEmail;
	}

	// Property accessors
	public long getOffsystemPendingOrderId() {
		return this.offsystemPendingOrderId;
	}

	public void setOffsystemPendingOrderId(long offsystemPendingOrderId) {
		this.offsystemPendingOrderId = offsystemPendingOrderId;
	}

	public Date getDateReceived() {
		return this.dateReceived;
	}

	public void setDateReceived(Date dateReceived) {
		this.dateReceived = dateReceived;
	}

	public String getOffsystemModule() {
		return this.offsystemModule;
	}

	public void setOffsystemModule(String offsystemModule) {
		this.offsystemModule = offsystemModule;
	}

	public Integer getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(Integer merchantId) {
		this.merchantId = merchantId;
	}

	public Integer getOffsystemStatus() {
		return this.offsystemStatus;
	}

	public void setOffsystemStatus(Integer offsystemStatus) {
		this.offsystemStatus = offsystemStatus;
	}

	public String getOffsystemDetails() {
		return this.offsystemDetails;
	}

	public void setOffsystemDetails(String offsystemDetails) {
		this.offsystemDetails = offsystemDetails;
	}

	public long getOffsystemNotificationOrderId() {
		return offsystemNotificationOrderId;
	}

	public void setOffsystemNotificationOrderId(
			long offsystemNotificationOrderId) {
		this.offsystemNotificationOrderId = offsystemNotificationOrderId;
	}

	public String getPayerEmail() {
		return payerEmail;
	}

	public void setPayerEmail(String payerEmail) {
		this.payerEmail = payerEmail;
	}

}
