/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.catalog;

// Generated Nov 5, 2008 10:22:34 PM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * ProductsPriceSpecials generated by hbm2java
 */
public class ProductPriceSpecial implements java.io.Serializable {

	private long productPriceId;

	private Date productPriceSpecialStartDate;

	private Date productPriceSpecialEndDate;

	private Integer productPriceSpecialDurationDays;

	private BigDecimal productPriceSpecialAmount;

	private BigDecimal originalPriceAmount;// transiant

	private boolean calculatePrice = true;

	// Constructors

	/** default constructor */
	public ProductPriceSpecial() {
	}

	/** minimal constructor */
	public ProductPriceSpecial(long productPriceId,
			BigDecimal productPriceSpecialAmount) {
		this.productPriceId = productPriceId;
		this.productPriceSpecialAmount = productPriceSpecialAmount;
	}

	/** full constructor */
	public ProductPriceSpecial(long productPriceId,
			Date productPriceSpecialStartDate, Date productPriceSpecialEndDate,
			Integer productPriceSpecialDurationDays,
			BigDecimal productPriceSpecialAmount) {
		this.productPriceId = productPriceId;
		this.productPriceSpecialStartDate = productPriceSpecialStartDate;
		this.productPriceSpecialEndDate = productPriceSpecialEndDate;
		this.productPriceSpecialDurationDays = productPriceSpecialDurationDays;
		this.productPriceSpecialAmount = productPriceSpecialAmount;
	}

	public long getProductPriceId() {
		return this.productPriceId;
	}

	public void setProductPriceId(long productPriceId) {
		this.productPriceId = productPriceId;
	}

	public Date getProductPriceSpecialStartDate() {
		return this.productPriceSpecialStartDate;
	}

	public void setProductPriceSpecialStartDate(
			Date productPriceSpecialStartDate) {
		this.productPriceSpecialStartDate = productPriceSpecialStartDate;
	}

	public Date getProductPriceSpecialEndDate() {
		return this.productPriceSpecialEndDate;
	}

	public void setProductPriceSpecialEndDate(Date productPriceSpecialEndDate) {
		this.productPriceSpecialEndDate = productPriceSpecialEndDate;
	}

	public Integer getProductPriceSpecialDurationDays() {
		return this.productPriceSpecialDurationDays;
	}

	public void setProductPriceSpecialDurationDays(
			Integer productPriceSpecialDurationDays) {
		this.productPriceSpecialDurationDays = productPriceSpecialDurationDays;
	}

	public BigDecimal getProductPriceSpecialAmount() {
		return this.productPriceSpecialAmount;
	}

	public void setProductPriceSpecialAmount(
			BigDecimal productPriceSpecialAmount) {
		this.productPriceSpecialAmount = productPriceSpecialAmount;
	}

	public boolean isCalculatePrice() {
		return calculatePrice;
	}

	public void setCalculatePrice(boolean calculatePrice) {
		this.calculatePrice = calculatePrice;
	}

	public BigDecimal getOriginalPriceAmount() {
		return originalPriceAmount;
	}

	public void setOriginalPriceAmount(BigDecimal originalPriceAmount) {
		this.originalPriceAmount = originalPriceAmount;
	}

}
