/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.catalog;

// Generated Sep 21, 2008 5:20:18 PM by Hibernate Tools 3.2.0.beta8

/**
 * ProductsOptionsValuesToProductsOptions generated by hbm2java
 */
public class ProductOptionValueToProductOption implements java.io.Serializable {

	// Fields

	private ProductOptionValueToProductOptionId id;

	// Constructors

	/** default constructor */
	public ProductOptionValueToProductOption() {
	}

	/** full constructor */
	public ProductOptionValueToProductOption(
			ProductOptionValueToProductOptionId id) {
		this.id = id;
	}

	// Property accessors
	public ProductOptionValueToProductOptionId getId() {
		return this.id;
	}

	public void setId(ProductOptionValueToProductOptionId id) {
		this.id = id;
	}

}
