/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.catalog;

// Generated May 19, 2010 2:04:19 PM by Hibernate Tools 3.2.4.GA

/**
 * ProductsPriceDescriptionId generated by hbm2java
 */
public class ProductPriceDescriptionId implements java.io.Serializable {

	private static final long serialVersionUID = 5799943131118045295L;
	private long productPriceId;
	private int languageId;

	public ProductPriceDescriptionId() {
	}

	public ProductPriceDescriptionId(long productPriceId, int languageId) {
		this.productPriceId = productPriceId;
		this.languageId = languageId;
	}

	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public long getProductPriceId() {
		return productPriceId;
	}

	public void setProductPriceId(long productPriceId) {
		this.productPriceId = productPriceId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + languageId;
		result = prime * result
				+ (int) (productPriceId ^ (productPriceId >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProductPriceDescriptionId other = (ProductPriceDescriptionId) obj;
		if (languageId != other.languageId)
			return false;
		if (productPriceId != other.productPriceId)
			return false;
		return true;
	}

}
