/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.catalog;

// Generated Sep 21, 2008 5:20:18 PM by Hibernate Tools 3.2.0.beta8

/**
 * ProductsOptionsValuesToProductsOptionsId generated by hbm2java
 */
public class ProductOptionValueToProductOptionId implements
		java.io.Serializable {

	// Fields

	private long productOptionId;

	private long productOptionValueId;

	// Constructors

	/** default constructor */
	public ProductOptionValueToProductOptionId() {
	}

	/** full constructor */
	public ProductOptionValueToProductOptionId(long productOptionId,
			long productOptionValueId) {
		this.productOptionId = productOptionId;
		this.productOptionValueId = productOptionValueId;
	}

	// Property accessors
	public long getProductOptionId() {
		return this.productOptionId;
	}

	public void setProductOptionId(long productOptionId) {
		this.productOptionId = productOptionId;
	}

	public long getProductOptionValueId() {
		return this.productOptionValueId;
	}

	public void setProductOptionValueId(long productOptionValueId) {
		this.productOptionValueId = productOptionValueId;
	}

	@Override
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result
				+ (int) (productOptionId ^ (productOptionId >>> 32));
		result = PRIME * result
				+ (int) (productOptionValueId ^ (productOptionValueId >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final ProductOptionValueToProductOptionId other = (ProductOptionValueToProductOptionId) obj;
		if (productOptionId != other.productOptionId)
			return false;
		if (productOptionValueId != other.productOptionValueId)
			return false;
		return true;
	}

}
