/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.catalog;

// Generated Oct 4, 2009 7:13:55 PM by Hibernate Tools 3.2.0.beta8

/**
 * ProductRelationship generated by hbm2java
 */
public class ProductRelationship implements java.io.Serializable {

	// Fields

	private long relationshipId;

	private int merchantId;

	private long productId;

	private long relatedProductId;

	private int relationshipType;

	private boolean relationshipActive;

	// Constructors

	/** default constructor */
	public ProductRelationship() {
	}

	/** full constructor */
	public ProductRelationship(long relationshipId, int merchantId,
			long productId, long relatedProductId, int relationshipType,
			boolean relationshipActive) {
		this.relationshipId = relationshipId;
		this.merchantId = merchantId;
		this.productId = productId;
		this.relatedProductId = relatedProductId;
		this.relationshipType = relationshipType;
		this.relationshipActive = relationshipActive;
	}

	// Property accessors
	public long getRelationshipId() {
		return this.relationshipId;
	}

	public void setRelationshipId(long relationshipId) {
		this.relationshipId = relationshipId;
	}

	public int getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(int merchantId) {
		this.merchantId = merchantId;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public long getRelatedProductId() {
		return this.relatedProductId;
	}

	public void setRelatedProductId(long relatedProductId) {
		this.relatedProductId = relatedProductId;
	}

	public int getRelationshipType() {
		return this.relationshipType;
	}

	public void setRelationshipType(int relationshipType) {
		this.relationshipType = relationshipType;
	}

	public boolean isRelationshipActive() {
		return this.relationshipActive;
	}

	public void setRelationshipActive(boolean relationshipActive) {
		this.relationshipActive = relationshipActive;
	}

}
