/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.catalog;

// Generated Sep 17, 2008 4:47:02 PM by Hibernate Tools 3.2.0.beta8

/**
 * ProductsOptionsValuesDescription generated by hbm2java
 */
public class ProductOptionValueDescription implements java.io.Serializable {

	// Fields

	private ProductOptionValueDescriptionId id;

	private String productOptionValueName;

	// Constructors

	/** default constructor */
	public ProductOptionValueDescription() {
	}

	/** full constructor */
	public ProductOptionValueDescription(ProductOptionValueDescriptionId id,
			String productOptionValueName) {
		this.id = id;
		this.productOptionValueName = productOptionValueName;
	}

	// Property accessors
	public ProductOptionValueDescriptionId getId() {
		return this.id;
	}

	public void setId(ProductOptionValueDescriptionId id) {
		this.id = id;
	}

	public String getProductOptionValueName() {
		return this.productOptionValueName;
	}

	public void setProductOptionValueName(String productOptionValueName) {
		this.productOptionValueName = productOptionValueName;
	}

}
