/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.catalog;

// Generated Nov 11, 2009 9:19:10 AM by Hibernate Tools 3.2.4.GA

/**
 * ReviewsDescriptionId generated by hbm2java
 */
public class ReviewDescriptionId implements java.io.Serializable {

	private long reviewId;
	private int languageId;

	public ReviewDescriptionId() {
	}

	public ReviewDescriptionId(long reviewId, int languageId) {
		this.reviewId = reviewId;
		this.languageId = languageId;
	}

	public long getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(long reviewId) {
		this.reviewId = reviewId;
	}

	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + languageId;
		result = prime * result + (int) (reviewId ^ (reviewId >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ReviewDescriptionId other = (ReviewDescriptionId) obj;
		if (languageId != other.languageId)
			return false;
		if (reviewId != other.reviewId)
			return false;
		return true;
	}

}
