/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.system;

// Generated Nov 11, 2009 9:19:10 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * CentralGroup generated by hbm2java
 */
public class CentralGroup implements java.io.Serializable {

	private Integer centralGroupId;
	private String centralGroupCode;
	private String centralGroupDescription;
	private byte centralGroupPosition;
	private boolean centralGroupVisible;
	private boolean centralGroupNew;
	private Date centralGroupNewUntil;
	private Date lastModified;

	public CentralGroup() {
	}

	public CentralGroup(String centralGroupCode, byte centralGroupPosition,
			boolean centralGroupVisible, boolean centralGroupNew) {
		this.centralGroupCode = centralGroupCode;
		this.centralGroupPosition = centralGroupPosition;
		this.centralGroupVisible = centralGroupVisible;
		this.centralGroupNew = centralGroupNew;
	}

	public CentralGroup(String centralGroupCode,
			String centralGroupDescription, byte centralGroupPosition,
			boolean centralGroupVisible, boolean centralGroupNew,
			Date centralGroupNewUntil, Date lastModified) {
		this.centralGroupCode = centralGroupCode;
		this.centralGroupDescription = centralGroupDescription;
		this.centralGroupPosition = centralGroupPosition;
		this.centralGroupVisible = centralGroupVisible;
		this.centralGroupNew = centralGroupNew;
		this.centralGroupNewUntil = centralGroupNewUntil;
		this.lastModified = lastModified;
	}

	public Integer getCentralGroupId() {
		return this.centralGroupId;
	}

	public void setCentralGroupId(Integer centralGroupId) {
		this.centralGroupId = centralGroupId;
	}

	public String getCentralGroupCode() {
		return this.centralGroupCode;
	}

	public void setCentralGroupCode(String centralGroupCode) {
		this.centralGroupCode = centralGroupCode;
	}

	public String getCentralGroupDescription() {
		return this.centralGroupDescription;
	}

	public void setCentralGroupDescription(String centralGroupDescription) {
		this.centralGroupDescription = centralGroupDescription;
	}

	public byte getCentralGroupPosition() {
		return this.centralGroupPosition;
	}

	public void setCentralGroupPosition(byte centralGroupPosition) {
		this.centralGroupPosition = centralGroupPosition;
	}

	public boolean isCentralGroupVisible() {
		return this.centralGroupVisible;
	}

	public void setCentralGroupVisible(boolean centralGroupVisible) {
		this.centralGroupVisible = centralGroupVisible;
	}

	public boolean isCentralGroupNew() {
		return this.centralGroupNew;
	}

	public void setCentralGroupNew(boolean centralGroupNew) {
		this.centralGroupNew = centralGroupNew;
	}

	public Date getCentralGroupNewUntil() {
		return this.centralGroupNewUntil;
	}

	public void setCentralGroupNewUntil(Date centralGroupNewUntil) {
		this.centralGroupNewUntil = centralGroupNewUntil;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}
