/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.system;

// Generated Nov 11, 2009 9:19:10 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * CentralFunction generated by hbm2java
 */
public class CentralFunction implements java.io.Serializable {

	private Integer centralFunctionId;
	private String centralFunctionCode;
	private String centralGroupCode;
	private String centralFunctionDescription;
	private byte centralFunctionPosition;
	private boolean centralFunctionVisible;
	private String centralFunctionUrl;
	private boolean centralFunctionNew;
	private Date centralFunctionNewUntil;
	private Date lastModified;
	private String role;

	public CentralFunction() {
	}

	public CentralFunction(String centralFunctionCode, String centralGroupCode,
			byte centralFunctionPosition, boolean centralFunctionVisible,
			boolean centralFunctionNew) {
		this.centralFunctionCode = centralFunctionCode;
		this.centralGroupCode = centralGroupCode;
		this.centralFunctionPosition = centralFunctionPosition;
		this.centralFunctionVisible = centralFunctionVisible;
		this.centralFunctionNew = centralFunctionNew;
	}

	public CentralFunction(String centralFunctionCode, String centralGroupCode,
			String centralFunctionDescription, byte centralFunctionPosition,
			boolean centralFunctionVisible, String centralFunctionUrl,
			boolean centralFunctionNew, Date centralFunctionNewUntil,
			Date lastModified) {
		this.centralFunctionCode = centralFunctionCode;
		this.centralGroupCode = centralGroupCode;
		this.centralFunctionDescription = centralFunctionDescription;
		this.centralFunctionPosition = centralFunctionPosition;
		this.centralFunctionVisible = centralFunctionVisible;
		this.centralFunctionUrl = centralFunctionUrl;
		this.centralFunctionNew = centralFunctionNew;
		this.centralFunctionNewUntil = centralFunctionNewUntil;
		this.lastModified = lastModified;
	}

	public Integer getCentralFunctionId() {
		return this.centralFunctionId;
	}

	public void setCentralFunctionId(Integer centralFunctionId) {
		this.centralFunctionId = centralFunctionId;
	}

	public String getCentralFunctionCode() {
		return this.centralFunctionCode;
	}

	public void setCentralFunctionCode(String centralFunctionCode) {
		this.centralFunctionCode = centralFunctionCode;
	}

	public String getCentralGroupCode() {
		return this.centralGroupCode;
	}

	public void setCentralGroupCode(String centralGroupCode) {
		this.centralGroupCode = centralGroupCode;
	}

	public String getCentralFunctionDescription() {
		return this.centralFunctionDescription;
	}

	public void setCentralFunctionDescription(String centralFunctionDescription) {
		this.centralFunctionDescription = centralFunctionDescription;
	}

	public byte getCentralFunctionPosition() {
		return this.centralFunctionPosition;
	}

	public void setCentralFunctionPosition(byte centralFunctionPosition) {
		this.centralFunctionPosition = centralFunctionPosition;
	}

	public boolean isCentralFunctionVisible() {
		return this.centralFunctionVisible;
	}

	public void setCentralFunctionVisible(boolean centralFunctionVisible) {
		this.centralFunctionVisible = centralFunctionVisible;
	}

	public String getCentralFunctionUrl() {
		return this.centralFunctionUrl;
	}

	public void setCentralFunctionUrl(String centralFunctionUrl) {
		this.centralFunctionUrl = centralFunctionUrl;
	}

	public boolean isCentralFunctionNew() {
		return this.centralFunctionNew;
	}

	public void setCentralFunctionNew(boolean centralFunctionNew) {
		this.centralFunctionNew = centralFunctionNew;
	}

	public Date getCentralFunctionNewUntil() {
		return this.centralFunctionNewUntil;
	}

	public void setCentralFunctionNewUntil(Date centralFunctionNewUntil) {
		this.centralFunctionNewUntil = centralFunctionNewUntil;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
