/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.system;

// Generated Dec 17, 2007 2:42:16 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

import com.salesmanager.core.util.DateUtil;

/**
 * CentralIntegrationErrors generated by hbm2java
 */
public class CentralIntegrationError implements java.io.Serializable {

	private long centralIntegrationErrorId;

	private int merchantid;

	private String centralIntegrationErrorDescription;

	private Date dateAdded;

	public CentralIntegrationError() {
	}

	public CentralIntegrationError(long centralIntegrationErrorId,
			int merchantid, Date dateAdded) {
		this.centralIntegrationErrorId = centralIntegrationErrorId;
		this.merchantid = merchantid;
		this.dateAdded = dateAdded;
	}

	public CentralIntegrationError(long centralIntegrationErrorId,
			int merchantid, String centralIntegrationErrorDescription,
			Date dateAdded) {
		this.centralIntegrationErrorId = centralIntegrationErrorId;
		this.merchantid = merchantid;
		this.centralIntegrationErrorDescription = centralIntegrationErrorDescription;
		this.dateAdded = dateAdded;
	}

	public long getCentralIntegrationErrorId() {
		return this.centralIntegrationErrorId;
	}

	public void setCentralIntegrationErrorId(long centralIntegrationErrorId) {
		this.centralIntegrationErrorId = centralIntegrationErrorId;
	}

	public int getMerchantid() {
		return this.merchantid;
	}

	public void setMerchantid(int merchantid) {
		this.merchantid = merchantid;
	}

	public String getCentralIntegrationErrorDescription() {
		return this.centralIntegrationErrorDescription;
	}

	public void setCentralIntegrationErrorDescription(
			String centralIntegrationErrorDescription) {
		this.centralIntegrationErrorDescription = centralIntegrationErrorDescription;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public String getDateAddedString() {
		return DateUtil.formatDate(this.getDateAdded());
	}

}
