/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.system;

// Generated Nov 8, 2008 9:09:19 AM by Hibernate Tools 3.2.0.beta8

/**
 * CentralSequencerId generated by hbm2java
 */
public class CentralSequencer implements java.io.Serializable {

	// Fields

	private static final long serialVersionUID = -1601510658666854761L;

	private int centralSequencerId;

	private long customersBasketIdNextValue;

	private long customersBasketAttributesIdNextValue;

	private long merchantConfigurationIdNextValue;

	private long merchantUserInformationIdNextValue;

	private long categoryIdNextValue;

	private long productIdNextValue;

	private long productOptionsIdNextValue;

	private long productAttributeIdNextValue;

	private long geoZoneIdNextValue;

	private long taxRateIdNextValue;

	private long productOptionIdNextValue;

	private long productOptionValuesIdNextValue;

	private long orderIdNextValue;

	private long customerIdNextValue;

	// Constructors

	/** default constructor */
	public CentralSequencer() {
	}

	/** full constructor */
	public CentralSequencer(int centralSequencerId,
			long customersBasketIdNextValue,
			long customersBasketAttributesIdNextValue,
			long merchantConfigurationIdNextValue,
			long merchantUserInformationIdNextValue, long categoryIdNextValue,
			long productIdNextValue, long productOptionsIdNextValue,
			long productAttributeIdNextValue, long geoZoneIdNextValue,
			long taxRateIdNextValue, long productOptionIdNextValue,
			long productOptionValuesIdNextValue, long orderIdNextValue,
			long customerIdNextValue) {
		this.centralSequencerId = centralSequencerId;
		this.customersBasketIdNextValue = customersBasketIdNextValue;
		this.customersBasketAttributesIdNextValue = customersBasketAttributesIdNextValue;
		this.merchantConfigurationIdNextValue = merchantConfigurationIdNextValue;
		this.merchantUserInformationIdNextValue = merchantUserInformationIdNextValue;
		this.categoryIdNextValue = categoryIdNextValue;
		this.productIdNextValue = productIdNextValue;
		this.productOptionsIdNextValue = productOptionsIdNextValue;
		this.productAttributeIdNextValue = productAttributeIdNextValue;
		this.geoZoneIdNextValue = geoZoneIdNextValue;
		this.taxRateIdNextValue = taxRateIdNextValue;
		this.productOptionIdNextValue = productOptionIdNextValue;
		this.productOptionValuesIdNextValue = productOptionValuesIdNextValue;
		this.orderIdNextValue = orderIdNextValue;
		this.customerIdNextValue = customerIdNextValue;
	}

	// Property accessors
	public long getCustomersBasketIdNextValue() {
		return this.customersBasketIdNextValue;
	}

	public void setCustomersBasketIdNextValue(long customersBasketIdNextValue) {
		this.customersBasketIdNextValue = customersBasketIdNextValue;
	}

	public long getCustomersBasketAttributesIdNextValue() {
		return this.customersBasketAttributesIdNextValue;
	}

	public void setCustomersBasketAttributesIdNextValue(
			long customersBasketAttributesIdNextValue) {
		this.customersBasketAttributesIdNextValue = customersBasketAttributesIdNextValue;
	}

	public long getMerchantConfigurationIdNextValue() {
		return this.merchantConfigurationIdNextValue;
	}

	public void setMerchantConfigurationIdNextValue(
			long merchantConfigurationIdNextValue) {
		this.merchantConfigurationIdNextValue = merchantConfigurationIdNextValue;
	}

	public long getMerchantUserInformationIdNextValue() {
		return this.merchantUserInformationIdNextValue;
	}

	public void setMerchantUserInformationIdNextValue(
			long merchantUserInformationIdNextValue) {
		this.merchantUserInformationIdNextValue = merchantUserInformationIdNextValue;
	}

	public long getCategoryIdNextValue() {
		return this.categoryIdNextValue;
	}

	public void setCategoryIdNextValue(long categoryIdNextValue) {
		this.categoryIdNextValue = categoryIdNextValue;
	}

	public long getProductIdNextValue() {
		return this.productIdNextValue;
	}

	public void setProductIdNextValue(long productIdNextValue) {
		this.productIdNextValue = productIdNextValue;
	}

	public long getProductOptionsIdNextValue() {
		return this.productOptionsIdNextValue;
	}

	public void setProductOptionsIdNextValue(long productOptionsIdNextValue) {
		this.productOptionsIdNextValue = productOptionsIdNextValue;
	}

	public long getProductAttributeIdNextValue() {
		return this.productAttributeIdNextValue;
	}

	public void setProductAttributeIdNextValue(long productAttributeIdNextValue) {
		this.productAttributeIdNextValue = productAttributeIdNextValue;
	}

	public long getGeoZoneIdNextValue() {
		return this.geoZoneIdNextValue;
	}

	public void setGeoZoneIdNextValue(long geoZoneIdNextValue) {
		this.geoZoneIdNextValue = geoZoneIdNextValue;
	}

	public long getTaxRateIdNextValue() {
		return this.taxRateIdNextValue;
	}

	public void setTaxRateIdNextValue(long taxRateIdNextValue) {
		this.taxRateIdNextValue = taxRateIdNextValue;
	}

	public long getProductOptionIdNextValue() {
		return this.productOptionIdNextValue;
	}

	public void setProductOptionIdNextValue(long productOptionIdNextValue) {
		this.productOptionIdNextValue = productOptionIdNextValue;
	}

	public long getProductOptionValuesIdNextValue() {
		return this.productOptionValuesIdNextValue;
	}

	public void setProductOptionValuesIdNextValue(
			long productOptionValuesIdNextValue) {
		this.productOptionValuesIdNextValue = productOptionValuesIdNextValue;
	}

	public long getOrderIdNextValue() {
		return this.orderIdNextValue;
	}

	public void setOrderIdNextValue(long orderIdNextValue) {
		this.orderIdNextValue = orderIdNextValue;
	}

	public long getCustomerIdNextValue() {
		return this.customerIdNextValue;
	}

	public void setCustomerIdNextValue(long customerIdNextValue) {
		this.customerIdNextValue = customerIdNextValue;
	}

	public int getCentralSequencerId() {
		return centralSequencerId;
	}

	public void setCentralSequencerId(int centralSequencerId) {
		this.centralSequencerId = centralSequencerId;
	}

	@Override
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result
				+ (int) (categoryIdNextValue ^ (categoryIdNextValue >>> 32));
		result = PRIME * result + centralSequencerId;
		result = PRIME * result
				+ (int) (customerIdNextValue ^ (customerIdNextValue >>> 32));
		result = PRIME
				* result
				+ (int) (customersBasketAttributesIdNextValue ^ (customersBasketAttributesIdNextValue >>> 32));
		result = PRIME
				* result
				+ (int) (customersBasketIdNextValue ^ (customersBasketIdNextValue >>> 32));
		result = PRIME * result
				+ (int) (geoZoneIdNextValue ^ (geoZoneIdNextValue >>> 32));
		result = PRIME
				* result
				+ (int) (merchantConfigurationIdNextValue ^ (merchantConfigurationIdNextValue >>> 32));
		result = PRIME
				* result
				+ (int) (merchantUserInformationIdNextValue ^ (merchantUserInformationIdNextValue >>> 32));
		result = PRIME * result
				+ (int) (orderIdNextValue ^ (orderIdNextValue >>> 32));
		result = PRIME
				* result
				+ (int) (productAttributeIdNextValue ^ (productAttributeIdNextValue >>> 32));
		result = PRIME * result
				+ (int) (productIdNextValue ^ (productIdNextValue >>> 32));
		result = PRIME
				* result
				+ (int) (productOptionIdNextValue ^ (productOptionIdNextValue >>> 32));
		result = PRIME
				* result
				+ (int) (productOptionValuesIdNextValue ^ (productOptionValuesIdNextValue >>> 32));
		result = PRIME
				* result
				+ (int) (productOptionsIdNextValue ^ (productOptionsIdNextValue >>> 32));
		result = PRIME * result
				+ (int) (taxRateIdNextValue ^ (taxRateIdNextValue >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final CentralSequencer other = (CentralSequencer) obj;
		if (categoryIdNextValue != other.categoryIdNextValue)
			return false;
		if (centralSequencerId != other.centralSequencerId)
			return false;
		if (customerIdNextValue != other.customerIdNextValue)
			return false;
		if (customersBasketAttributesIdNextValue != other.customersBasketAttributesIdNextValue)
			return false;
		if (customersBasketIdNextValue != other.customersBasketIdNextValue)
			return false;
		if (geoZoneIdNextValue != other.geoZoneIdNextValue)
			return false;
		if (merchantConfigurationIdNextValue != other.merchantConfigurationIdNextValue)
			return false;
		if (merchantUserInformationIdNextValue != other.merchantUserInformationIdNextValue)
			return false;
		if (orderIdNextValue != other.orderIdNextValue)
			return false;
		if (productAttributeIdNextValue != other.productAttributeIdNextValue)
			return false;
		if (productIdNextValue != other.productIdNextValue)
			return false;
		if (productOptionIdNextValue != other.productOptionIdNextValue)
			return false;
		if (productOptionValuesIdNextValue != other.productOptionValuesIdNextValue)
			return false;
		if (productOptionsIdNextValue != other.productOptionsIdNextValue)
			return false;
		if (taxRateIdNextValue != other.taxRateIdNextValue)
			return false;
		return true;
	}

}
