package com.salesmanager.central.entity.reference;

// Generated Oct 2, 2007 10:47:54 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * CentralCountriesStatus generated by hbm2java
 */
public class CentralCountriesStatus implements java.io.Serializable {

	private int centralCountriesStatusId;
	private int countriesId;
	private int centralCountriesStatusCode;
	private String centralCountriesCode;
	private Date dateAdded;

	public CentralCountriesStatus() {
	}

	public CentralCountriesStatus(int centralCountriesStatusId,
			int countriesId, int centralCountriesStatusCode,
			String centralCountriesCode, Date dateAdded) {
		this.centralCountriesStatusId = centralCountriesStatusId;
		this.countriesId = countriesId;
		this.centralCountriesStatusCode = centralCountriesStatusCode;
		this.centralCountriesCode = centralCountriesCode;
		this.dateAdded = dateAdded;
	}

	public int getCentralCountriesStatusId() {
		return this.centralCountriesStatusId;
	}

	public void setCentralCountriesStatusId(int centralCountriesStatusId) {
		this.centralCountriesStatusId = centralCountriesStatusId;
	}

	public int getCountriesId() {
		return this.countriesId;
	}

	public void setCountriesId(int countriesId) {
		this.countriesId = countriesId;
	}

	public int getCentralCountriesStatusCode() {
		return this.centralCountriesStatusCode;
	}

	public void setCentralCountriesStatusCode(int centralCountriesStatusCode) {
		this.centralCountriesStatusCode = centralCountriesStatusCode;
	}

	public String getCentralCountriesCode() {
		return this.centralCountriesCode;
	}

	public void setCentralCountriesCode(String centralCountriesCode) {
		this.centralCountriesCode = centralCountriesCode;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
