-- Upgrade from version 1.1.2 to version 1.1.3

-- This file contains sql for Oracle and MySQL

------------
-- Oracle --
------------
ALTER SESSION set NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';


-- DROP TABLE PORTLET CASCADE CONSTRAINTS;

PROMPT Creating Table PORTLET ...
CREATE TABLE PORTLET (
  PORTLET_ID NUMBER(10,0) NOT NULL,
  MERCHANT_ID NUMBER(10,0) NOT NULL,
  PAGE NUMBER(10,0) NOT NULL,
  TITLE VARCHAR2(60 CHAR) NOT NULL,
  NAME VARCHAR2(100 CHAR),
  PORTLET_TYPE NUMBER(10,0) DEFAULT '0',
  LABEL_ID NUMBER(10,0) NOT NULL,
  VISIBLE NUMBER(3,0) DEFAULT '0',
  ENABLED NUMBER(3,0) DEFAULT '1',
  SORT_ORDER NUMBER(10,0) DEFAULT '0',
  COLUMN_ID VARCHAR2(20 CHAR) NOT NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_T_PORTLET on table PORTLET ... 
ALTER TABLE PORTLET
ADD CONSTRAINT PRIMARY_T_PORTLET PRIMARY KEY
(
  PORTLET_ID
)
ENABLE
;
PROMPT Creating Index IDX_PORTLET_LABEL_ID_SM on PORTLET ...
CREATE INDEX IDX_PORTLET_LABEL_ID_SM ON PORTLET
(
  MERCHANT_ID,
  LABEL_ID
) 
;
PROMPT Creating Index IDX_PORTLET_MERCHANT_ID_SM on PORTLET ...
CREATE INDEX IDX_PORTLET_MERCHANT_ID_SM ON PORTLET
(
  MERCHANT_ID
) 
;
PROMPT Creating Index IDX_PORTLET_PAGE_ID_SM on PORTLET ...
CREATE INDEX IDX_PORTLET_PAGE_ID_SM ON PORTLET
(
  MERCHANT_ID,
  PAGE
) 
;
PROMPT Creating Index IDX_PORTLET_PG_COL_ID_SM on PORTLET ...
CREATE INDEX IDX_PORTLET_PG_COL_ID_SM ON PORTLET
(
  MERCHANT_ID,
  PAGE,
  COLUMN_ID
) 
;



-- DROP TABLE PAGE CASCADE CONSTRAINTS;


PROMPT Creating Table PAGE ...
CREATE TABLE PAGE (
  PAGE_ID NUMBER(10,0) NOT NULL,
  MERCHANT_ID NUMBER(10,0) NOT NULL,
  HEADER CLOB,
  TITLE VARCHAR2(60 CHAR) NOT NULL,
  NAME VARCHAR2(100 CHAR),
  VISIBLE NUMBER(3,0) DEFAULT '0',
  ENABLED NUMBER(3,0) DEFAULT '1',
  SECURED NUMBER(3,0) DEFAULT '0',
  STYLE NUMBER(10,0) NOT NULL,
  PROPERTY1 VARCHAR2(120 CHAR) NULL,
  PROPERTY2 VARCHAR2(120 CHAR) NULL,
  PROPERTY3 VARCHAR2(120 CHAR) NULL,
  PROPERTY4 VARCHAR2(120 CHAR) NULL,
  PROPERTY5 VARCHAR2(120 CHAR) NULL,
  PROPERTY6 VARCHAR2(120 CHAR) NULL,
  PROPERTY7 VARCHAR2(120 CHAR) NULL,
  PROPERTY8 VARCHAR2(120 CHAR) NULL,
  PROPERTY9 VARCHAR2(120 CHAR) NULL,
  PROPERTY10 VARCHAR2(120 CHAR) NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_T_PAGE on table PAGE ... 
ALTER TABLE PAGE
ADD CONSTRAINT PRIMARY_T_PAGE PRIMARY KEY
(
  PAGE_ID
)
ENABLE
;
PROMPT Creating Index IDX_PAGE_MERCHANT_ID_SM on PAGE ...
CREATE INDEX IDX_PAGE_MERCHANT_ID_SM ON PAGE
(
  PAGE_ID,
  MERCHANT_ID
) 
;
PROMPT Creating Index IDX_TITLE_MERCHANT_ID_SM on PAGE ...
CREATE INDEX IDX_TITLE_MERCHANT_ID_SM ON PAGE
(
  TITLE,
  MERCHANT_ID
) 
;

ALTER TABLE CENTRAL_SEQUENCER ADD PORTLET_ID_NEXT_VALUE NUMBER(10,0) DEFAULT '0' NOT NULL;
ALTER TABLE CENTRAL_SEQUENCER ADD PAGE_ID_NEXT_VALUE NUMBER(10,0) DEFAULT '0' NOT NULL;
ALTER TABLE CENTRAL_SEQUENCER ADD PAGEFLOW_ID_NEXT_VALUE NUMBER(10,0) DEFAULT '0' NOT NULL;
ALTER TABLE PRODUCTS ADD PRODUCTS_EXTERNAL_DL VARCHAR2(120 CHAR) NULL;
ALTER TABLE PRODUCTS_DESCRIPTION ADD PRODUCTS_EXTERNAL_DL VARCHAR2(120 CHAR) NULL;


-----------
-- MySQL --
-----------

CREATE TABLE PORTLET (
	PORTLET_ID INT(11) NOT NULL,
	MERCHANT_ID INT(11) NOT NULL,
	PAGE INT(11) NOT NULL,
	TITLE VARCHAR(60) NOT NULL,
	NAME VARCHAR(100) NULL,
	PORTLET_TYPE INT(3) DEFAULT 0,
	LABEL_ID INT(11) NOT NULL,
	VISIBLE TINYINT(1) DEFAULT '0',
	ENABLED TINYINT(1) DEFAULT '1',
	SORT_ORDER INT(3) DEFAULT 0,
	COLUMN_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (PORTLET_ID),
	KEY IDX_PORTLET_MERCHANT_ID_SM (MERCHANT_ID),
	KEY IDX_PORTLET_PAGE_ID_SM (MERCHANT_ID, PAGE),
	KEY IDX_PORTLET_PG_COL_ID_SM (MERCHANT_ID, PAGE, COLUMN_ID),
	KEY IDX_PORTLET_LABEL_ID_SM (MERCHANT_ID, LABEL_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


CREATE TABLE PAGE (
	PAGE_ID INT(11) NOT NULL,
	MERCHANT_ID INT(11) NOT NULL,
	HEADER TEXT CHARACTER SET UTF8,
	TITLE VARCHAR(60) NOT NULL,
	NAME VARCHAR(100) NULL,
	VISIBLE TINYINT(1) DEFAULT '0',
	ENABLED TINYINT(1) DEFAULT '1',
      SECURED TINYINT(1) DEFAULT '0',
	STYLE INT(4) NOT NULL,
	PROPERTY1 VARCHAR(120) NULL,
	PROPERTY2 VARCHAR(120) NULL,
	PROPERTY3 VARCHAR(120) NULL,   
	PROPERTY4 VARCHAR(120) NULL, 
	PROPERTY5 VARCHAR(120) NULL,
      PROPERTY6 VARCHAR(120) NULL,
      PROPERTY7 VARCHAR(120) NULL,
      PROPERTY8 VARCHAR(120) NULL,
      PROPERTY9 VARCHAR(120) NULL,
      PROPERTY10 VARCHAR(120) NULL, 
	PRIMARY KEY (PAGE_ID),
	KEY IDX_PAGE_MERCHANT_ID_SM (PAGE_ID,MERCHANT_ID),
	KEY IDX_TITLE_MERCHANT_ID_SM (TITLE,MERCHANT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

ALTER TABLE CENTRAL_SEQUENCER ADD COLUMN PORTLET_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0';
ALTER TABLE CENTRAL_SEQUENCER ADD COLUMN PAGE_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0';
ALTER TABLE CENTRAL_SEQUENCER ADD COLUMN PAGEFLOW_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0';
ALTER TABLE PRODUCTS ADD COLUMN PRODUCTS_EXTERNAL_DL VARCHAR(120) NULL;
ALTER TABLE PRODUCTS_DESCRIPTION ADD COLUMN PRODUCTS_EXTERNAL_DL VARCHAR(120) NULL;

-----------------------------
---DATA (Oracle and MySQL)---
-----------------------------
UPDATE CENTRAL_SEQUENCER SET PAGE_ID_NEXT_VALUE=200;

INSERT INTO PAGE (PAGE_ID,MERCHANT_ID,TITLE,VISIBLE,ENABLED,STYLE,PROPERTY1) values (200,1,'FB',1,1,1,'basic.jsp');
INSERT INTO CORE_MODULES_SERVICES VALUES(1000,200,'merchantlogo','XX',1,'Merchant Logo','',1,0,0,'','','','','','','','','',0);
INSERT INTO CORE_MODULES_SERVICES VALUES(1001,200,'friendslist','XX',1,'Facebook friends list','',1,0,0,'','','','','','','','','',0);
INSERT INTO CORE_MODULES_SERVICES VALUES(1002,200,'productslider','XX',1,'Facebook product list','',1,0,0,'','','','','','','','','',0);
INSERT INTO CORE_MODULES_SERVICES VALUES(1003,200,'downloadproducts','XX',1,'Facebook download product list','',1,0,0,'','','','','','','','','',0);
INSERT INTO CORE_MODULES_SERVICES VALUES(1004,200,'fancontent','XX',1,'Displayed to page fans only','',1,0,0,'','','','','','','','','',0);
INSERT INTO CORE_MODULES_SERVICES VALUES(1005,200,'anonymouscontent','XX',1,'Displayed to anonymous users only','',1,0,0,'','','','','','','','','',0);

INSERT INTO CENTRAL_GROUP VALUES(10, 'INT', '/integration/integration.action', 3, 1, 0, '2010-01-01 00:00:00', '2010-01-01 00:00:00');
INSERT INTO CENTRAL_REG_ASSOCIATION VALUES(80, 1, 'INT', ' ', 0, '2010-01-01 00:00:00');
INSERT INTO CENTRAL_REG_ASSOCIATION VALUES(81, 2, 'INT', ' ', 0, '2010-01-01 00:00:00');

INSERT INTO CENTRAL_FUNCTION VALUES(40, 'INTFBPO01', 'INT', 'Integration - Facebook fan page', 10, 1, '/integration/fbportlet.action', 0, '2010-01-01 00:00:00', '2010-01-01 00:00:00');
INSERT INTO CENTRAL_REG_ASSOCIATION VALUES(70, 1, ' ', 'INTFBPO01', 0, '2010-01-01 00:00:00');
INSERT INTO CENTRAL_REG_ASSOCIATION VALUES(71, 2, ' ', 'INTFBPO01', 0, '2010-01-01 00:00:00');

INSERT INTO CENTRAL_FUNCTION VALUES(41, 'INTKEYO01', 'INT', 'Integration - integration keys', 0, 1, '/integration/integrationKeys.action', 0, '2010-01-01 00:00:00', '2010-01-01 00:00:00');
INSERT INTO CENTRAL_REG_ASSOCIATION VALUES(72, 1, ' ', 'INTKEYO01', 0, '2010-01-01 00:00:00');
INSERT INTO CENTRAL_REG_ASSOCIATION VALUES(73, 2, ' ', 'INTKEYO01', 0, '2010-01-01 00:00:00');

UPDATE CENTRAL_FUNCTION set CENTRAL_GROUP_CODE='INT', CENTRAL_FUNCTION_POSITION=100 WHERE CENTRAL_FUNCTION_CODE='CAROP02';
UPDATE CENTRAL_FUNCTION set CENTRAL_FUNCTION_URL='/catalog/relationship.action' WHERE CENTRAL_FUNCTION_CODE='SFRONT02';

INSERT INTO MODULE_CONFIGURATION (
  CONFIGURATION_MODULE,
  CONFIGURATION_KEY,
  COUNTRY_ISO_CODE_2,
  CONFIGURATION_VALUE
) values
('friendslist','fields','XX','{"fields":[{"field":{"type":"text","label":"Invitation type text","name":"invitationType"}},{"field":{"type":"text","label":"Action text","name":"actionText"}}]}');

INSERT INTO MODULE_CONFIGURATION (
  CONFIGURATION_MODULE,
  CONFIGURATION_KEY,
  COUNTRY_ISO_CODE_2,
  CONFIGURATION_VALUE
) values
('productslider','fields','XX','{"fields":[{"field":{"type":"text","label":"Relation type id","name":"relationType"}}]}');

INSERT INTO MODULE_CONFIGURATION (
  CONFIGURATION_MODULE,
  CONFIGURATION_KEY,
  COUNTRY_ISO_CODE_2,
  CONFIGURATION_VALUE
) values
('downloadproducts','fields','XX','{"fields":[{"field":{"type":"text","label":"Relation type id","name":"downloadRelationType"}},{"field":{"type":"radio","label":"Downloads accessibility","name":"downloadsAccess","values":[{"name":"downloadsAccess","value":"All users"},{"name":"downloadsAccess","value":"Fans only"}]}}]}');

INSERT INTO MODULE_CONFIGURATION (
  CONFIGURATION_MODULE,
  CONFIGURATION_KEY,
  COUNTRY_ISO_CODE_2,
  CONFIGURATION_VALUE
) values
('fancontent','fields','XX','{"fields":[{"field":{"type":"text","label":"Label title","name":"fanContentLabelTitle"}}]}');

INSERT INTO MODULE_CONFIGURATION (
  CONFIGURATION_MODULE,
  CONFIGURATION_KEY,
  COUNTRY_ISO_CODE_2,
  CONFIGURATION_VALUE
) values
('anonymouscontent','fields','XX','{"fields":[{"field":{"type":"text","label":"Label title","name":"anonymousContentLabelTitle"}}]}');