-- Upgrade from version 1.1.3 to version 1.1.4

-- This file contains sql for Oracle and MySQL

------------
-- Oracle --
------------
ALTER SESSION set NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

alter table ORDERS ADD DISPLAY_INVOICE_PAYMENTS NUMBER(3,0) DEFAULT '0';

alter table DYNAMIC_LABEL ADD IMAGE VARCHAR2(60 CHAR);

alter table PRODUCTS add PRODUCTS_IMAGE_1 VARCHAR2(64 CHAR);
alter table PRODUCTS add PRODUCTS_IMAGE_2 VARCHAR2(64 CHAR);
alter table PRODUCTS add PRODUCTS_IMAGE_3 VARCHAR2(64 CHAR);
alter table PRODUCTS add PRODUCTS_IMAGE_4 VARCHAR2(64 CHAR);
alter table PRODUCTS add PRODUCT_REVIEW_AVG FLOAT NULL;
alter table PRODUCTS add PRODUCT_REVIEW_COUNT NUMBER(10,0) DEFAULT 0;
alter table PRODUCTS_DESCRIPTION add PRODUCTS_TITLE VARCHAR2(120 CHAR) NULL;
alter table CATEGORIES_DESCRIPTION add CATEGORIES_TITLE VARCHAR2(120 CHAR) NULL;

insert into MODULE_CONFIGURATION (
  CONFIGURATION_MODULE,
  CONFIGURATION_KEY,
  COUNTRY_ISO_CODE_2,
  CONFIGURATION_VALUE
) values
('decotemplate','slider','XX','992px x 371px');


-----------------------------
---DATA (Oracle and MySQL)---
-----------------------------

alter table ORDERS ADD COLUMN DISPLAY_INVOICE_PAYMENTS TINYINT(1) NOT NULL DEFAULT '0';

alter table DYNAMIC_LABEL ADD COLUMN IMAGE VARCHAR(60) NULL;

alter table PRODUCTS add COLUMN PRODUCTS_IMAGE_1 VARCHAR(64) DEFAULT NULL;
alter table PRODUCTS add COLUMN PRODUCTS_IMAGE_2 VARCHAR(64) DEFAULT NULL;
alter table PRODUCTS add COLUMN PRODUCTS_IMAGE_3 VARCHAR(64) DEFAULT NULL;
alter table PRODUCTS add COLUMN PRODUCTS_IMAGE_4 VARCHAR(64) DEFAULT NULL;
alter table PRODUCTS add COLUMN PRODUCT_REVIEW_AVG DECIMAL(5,1) NULL;
alter table PRODUCTS add COLUMN PRODUCT_REVIEW_COUNT INT(10) DEFAULT 0;
alter table PRODUCTS_DESCRIPTION add COLUMN PRODUCTS_TITLE VARCHAR(120) NULL;
alter table CATEGORIES_DESCRIPTION add COLUMN CATEGORIES_TITLE VARCHAR(120) NULL;

insert into MODULE_CONFIGURATION (
  CONFIGURATION_MODULE,
  CONFIGURATION_KEY,
  COUNTRY_ISO_CODE_2,
  CONFIGURATION_VALUE
) values
('decotemplate','slider','XX','992px x 371px');
