/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.merchant;

// Generated Jul 31, 2008 5:06:08 PM by Hibernate Tools 3.2.0.b9

/**
 * MerchantUserRole generated by hbm2java
 */
public class MerchantUserRole implements java.io.Serializable {

	private String adminName;

	private String roleCode;

	private long merchantUserRoleId;

	public MerchantUserRole() {
	}

	public MerchantUserRole(long merchantUserRoleId, String adminName,
			String roleCode) {
		this.merchantUserRoleId = merchantUserRoleId;
		this.adminName = adminName;
		this.roleCode = roleCode;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getAdminName() {
		return adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public long getMerchantUserRoleId() {
		return merchantUserRoleId;
	}

	public void setMerchantUserRoleId(long merchantUserRoleId) {
		this.merchantUserRoleId = merchantUserRoleId;
	}

}
