package com.salesmanager.core.entity.merchant;
// Generated Oct 27, 2010 10:12:36 PM by Hibernate Tools 3.2.4.GA



/**
 * MerchantUserRoleDef generated by hbm2java
 */
public class MerchantUserRoleDef  implements java.io.Serializable {


     private int roleid;
     private String roleCode;
     private String roleDescription;

    public MerchantUserRoleDef() {
    }

	
    public MerchantUserRoleDef(String roleCode) {
        this.roleCode = roleCode;
    }
    public MerchantUserRoleDef(String roleCode, String roleDescription) {
       this.roleCode = roleCode;
       this.roleDescription = roleDescription;
    }
   
    public int getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(int roleid) {
        this.roleid = roleid;
    }
    public String getRoleCode() {
        return this.roleCode;
    }
    
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }




}


