/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.merchant;

// Generated Nov 29, 2007 2:11:20 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * MerchantConfiguration generated by hbm2java
 */
public class MerchantConfiguration implements java.io.Serializable {

	private long configurationId;
	private int merchantId;
	private String configurationModule;
	private String configurationKey;
	private String configurationValue;
	private String configurationValue1;
	private String configurationValue2;
	private Date lastModified;
	private Date dateAdded;
	private Integer sortOrder;

	private void initialize() {
		Date dt = new Date();
		this.setDateAdded(new Date(dt.getTime()));
		this.setLastModified(new Date(dt.getTime()));
	}

	public MerchantConfiguration() {
		initialize();
	}

	public MerchantConfiguration(long configurationId, int merchantId,
			String configurationModule, String configurationKey,
			String configurationValue, String configurationValue1,
			String configurationValue2, Date lastModified, Date dateAdded,
			Integer sortOrder) {
		this.configurationId = configurationId;
		this.merchantId = merchantId;
		this.configurationModule = configurationModule;
		this.configurationKey = configurationKey;
		this.configurationValue = configurationValue;
		this.configurationValue1 = configurationValue1;
		this.configurationValue2 = configurationValue2;
		this.lastModified = lastModified;
		this.dateAdded = dateAdded;
		this.sortOrder = sortOrder;
	}

	public long getConfigurationId() {
		return this.configurationId;
	}

	public void setConfigurationId(long configurationId) {
		this.configurationId = configurationId;
	}

	public int getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(int merchantId) {
		this.merchantId = merchantId;
	}

	public String getConfigurationModule() {
		return this.configurationModule;
	}

	public void setConfigurationModule(String configurationModule) {
		this.configurationModule = configurationModule;
	}

	public String getConfigurationKey() {
		return this.configurationKey;
	}

	public void setConfigurationKey(String configurationKey) {
		this.configurationKey = configurationKey;
	}

	public String getConfigurationValue() {
		return this.configurationValue;
	}

	public void setConfigurationValue(String configurationValue) {
		this.configurationValue = configurationValue;
	}

	public String getConfigurationValue1() {
		return this.configurationValue1;
	}

	public void setConfigurationValue1(String configurationValue1) {
		this.configurationValue1 = configurationValue1;
	}

	public String getConfigurationValue2() {
		return this.configurationValue2;
	}

	public void setConfigurationValue2(String configurationValue2) {
		this.configurationValue2 = configurationValue2;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public Integer getSortOrder() {
		return sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

}
