/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.merchant;

// Generated Aug 13, 2007 8:24:10 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * MerchantRegistration generated by hbm2java
 */
public class MerchantRegistration implements java.io.Serializable {

	private int merchantId;
	private int merchantRegistrationDefCode;
	private String token;
	private String ccType;
	private String ccOwner;
	private String ccNumber;
	private String ccExpires;
	private byte[] ccCvv;
	private Date lastModified;
	private Date dateAdded;
	private Integer promoCode;
	private Date promoCodeExpiry;

	public MerchantRegistration() {
	}

	public MerchantRegistration(int merchantId,
			int merchantRegistrationDefCode, Date dateAdded,
			Date promoCodeExpiry) {
		this.merchantRegistrationDefCode = merchantRegistrationDefCode;
		this.dateAdded = dateAdded;
		this.promoCodeExpiry = promoCodeExpiry;
		this.merchantId = merchantId;
	}

	public MerchantRegistration(int merchantId,
			int merchantRegistrationDefCode, String token, String ccType,
			String ccOwner, String ccNumber, String ccExpires, byte[] ccCvv,
			Date lastModified, Date dateAdded, Integer promoCode,
			Date promoCodeExpiry) {
		this.merchantId = merchantId;
		this.merchantRegistrationDefCode = merchantRegistrationDefCode;
		this.token = token;
		this.ccType = ccType;
		this.ccOwner = ccOwner;
		this.ccNumber = ccNumber;
		this.ccExpires = ccExpires;
		this.ccCvv = ccCvv;
		this.lastModified = lastModified;
		this.dateAdded = dateAdded;
		this.promoCode = promoCode;
		this.promoCodeExpiry = promoCodeExpiry;
	}

	public int getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(int merchantId) {
		this.merchantId = merchantId;
	}

	public int getMerchantRegistrationDefCode() {
		return this.merchantRegistrationDefCode;
	}

	public void setMerchantRegistrationDefCode(int merchantRegistrationDefCode) {
		this.merchantRegistrationDefCode = merchantRegistrationDefCode;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getCcType() {
		return this.ccType;
	}

	public void setCcType(String ccType) {
		this.ccType = ccType;
	}

	public String getCcOwner() {
		return this.ccOwner;
	}

	public void setCcOwner(String ccOwner) {
		this.ccOwner = ccOwner;
	}

	public String getCcNumber() {
		return this.ccNumber;
	}

	public void setCcNumber(String ccNumber) {
		this.ccNumber = ccNumber;
	}

	public String getCcExpires() {
		return this.ccExpires;
	}

	public void setCcExpires(String ccExpires) {
		this.ccExpires = ccExpires;
	}

	public byte[] getCcCvv() {
		return this.ccCvv;
	}

	public void setCcCvv(byte[] ccCvv) {
		this.ccCvv = ccCvv;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public Integer getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(Integer promoCode) {
		this.promoCode = promoCode;
	}

	public Date getPromoCodeExpiry() {
		return this.promoCodeExpiry;
	}

	public void setPromoCodeExpiry(Date promoCodeExpiry) {
		this.promoCodeExpiry = promoCodeExpiry;
	}

	public String toString() {
		return new StringBuffer().append("merchantid ").append(this.merchantId)
				.append(" registrationCode ").append(
						this.merchantRegistrationDefCode).append(" cctype ")
				.append(this.ccType).append(" ccowner ").append(this.ccOwner)
				.append(" ccnumber ").append(this.ccNumber).append(
						" ccexpires ").append(this.ccExpires).append(" ccCvv ")
				.append(this.ccCvv).append(" promoCode ")
				.append(this.promoCode).append(" promoExpiry").append(
						this.promoCodeExpiry).toString();
	}

}
