SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- DATABASE: 'SALESMANAGER'
--
-- --------------------------------------------------------



-- --------------------------------------------------------
--
-- TABLE STRUCTURE FOR TABLE 'CATEGORIES'
--

CREATE TABLE CATEGORIES (
CATEGORIES_ID INT(11) NOT NULL,
CATEGORIES_IMAGE VARCHAR(64) DEFAULT NULL,
PARENT_ID INT(11) NOT NULL DEFAULT '0',
SORT_ORDER INT(3) DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT NULL,
LAST_MODIFIED DATETIME DEFAULT NULL,
CATEGORIES_STATUS TINYINT(1) DEFAULT '1',
VISIBLE TINYINT(1) DEFAULT '1',
REFCATEGORYID INT(11),
REFCATEGORYLEVEL INT(3),
REFCATEGORYNAME VARCHAR(255),
REFCATEGORYPARENTID VARCHAR(11),
REFEXPIRED VARCHAR(5),
MERCHANTID INT(11) NOT NULL DEFAULT '0',
DEPTH INT(2) DEFAULT '0',
LINEAGE TEXT COLLATE LATIN1_GENERAL_CI NULL,
PRIMARY KEY (CATEGORIES_ID),
KEY IDX_PARENT_ID_CAT_ID_SM (PARENT_ID,CATEGORIES_ID),
KEY IDX_STATUS_CAT_SM (CATEGORIES_STATUS),
KEY IDX_SORT_ORDER_SM (SORT_ORDER),
KEY IDX_MERCHANT_ID_SM (MERCHANTID),
KEY IDX_MERCHANT_ID_LINEAGE (MERCHANTID,LINEAGE(512))
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------
--
-- TABLE STRUCTURE FOR TABLE 'CATEGORIES_DESCRIPTION'
--

CREATE TABLE CATEGORIES_DESCRIPTION (
CATEGORIES_ID INT(11) NOT NULL DEFAULT '0',
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
CATEGORIES_NAME VARCHAR(32) CHARACTER SET UTF8 NOT NULL DEFAULT '',
CATEGORIES_DESCRIPTION TEXT CHARACTER SET UTF8,
SE_URL_SRC VARCHAR(100) NULL,
SE_URL VARCHAR(100) NULL,
METATAG_TITLE VARCHAR(255) DEFAULT '' NULL,
METATAG_KEYWORDS TEXT COLLATE LATIN1_GENERAL_CI NULL,
METATAG_DESCRIPTION TEXT COLLATE LATIN1_GENERAL_CI NULL,
CATEGORIES_TITLE VARCHAR(120) NULL,
PRIMARY KEY (CATEGORIES_ID,LANGUAGE_ID),
KEY IDX_CATEGORIES_NAME_SM (CATEGORIES_NAME),
KEY IDX_CATEGORIES_ID_SM (CATEGORIES_ID),
KEY IDX_CATEGORIES_SE_SM (SE_URL)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CENTRAL_CHANNELS'
--

CREATE TABLE CENTRAL_CHANNELS (
CENTRAL_CHANNELS_ID INT(3) NOT NULL AUTO_INCREMENT,
CENTRAL_CHANNEL_CODE INT(3) NOT NULL DEFAULT '1',
CENTRAL_CHANNEL_DESCRIPTION VARCHAR(40) DEFAULT NULL,
CENTRAL_CHANNEL_POSITION TINYINT(3) DEFAULT '0',
CENTRAL_CHANNEL_VISIBLE TINYINT(1) DEFAULT '0',
LAST_MODIFIED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (CENTRAL_CHANNELS_ID),
UNIQUE KEY UNQ_CHANNEL_GROUP_KEY (CENTRAL_CHANNEL_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CENTRAL_COUNTRIES_STATUS'
--

CREATE TABLE CENTRAL_COUNTRIES_STATUS (
CENTRAL_COUNTRIES_STATUS_ID INT(11) NOT NULL AUTO_INCREMENT,
COUNTRIES_ID INT(11) NOT NULL,
CENTRAL_COUNTRIES_STATUS_CODE INT(2) DEFAULT '-1',
CENTRAL_COUNTRIES_CODE CHAR(2) DEFAULT '0',
DATE_ADDED DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (CENTRAL_COUNTRIES_STATUS_ID),
KEY IDX_CENTRAL_COUNTRIES_STATUS (CENTRAL_COUNTRIES_STATUS_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CENTRAL_CREDIT_CARDS'
--

CREATE TABLE CENTRAL_CREDIT_CARDS (
CENTRAL_CREDIT_CARDS_ID INT(3) NOT NULL AUTO_INCREMENT,
CENTRAL_CREDIT_CARDS_CODE VARCHAR(3) DEFAULT '1',
CENTRAL_CREDIT_CARDS_DESC VARCHAR(40) DEFAULT NULL,
CENTRAL_CREDIT_CARDS_POSITION TINYINT(3) DEFAULT '0',
CENTRAL_CREDIT_CARDS_VISIBLE TINYINT(1) DEFAULT '0',
LAST_MODIFIED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (CENTRAL_CREDIT_CARDS_ID),
UNIQUE KEY UNQ_CCARD_KEY (CENTRAL_CREDIT_CARDS_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CENTRAL_FUNCTION'
--

CREATE TABLE CENTRAL_FUNCTION (
CENTRAL_FUNCTION_ID INT(5) NOT NULL AUTO_INCREMENT,
CENTRAL_FUNCTION_CODE VARCHAR(10) DEFAULT '',
CENTRAL_GROUP_CODE VARCHAR(10) DEFAULT '',
CENTRAL_FUNCTION_DESCRIPTION VARCHAR(40) DEFAULT NULL,
CENTRAL_FUNCTION_POSITION TINYINT(3) DEFAULT '0',
CENTRAL_FUNCTION_VISIBLE TINYINT(1) DEFAULT '0',
CENTRAL_FUNCTION_URL VARCHAR(255) DEFAULT NULL,
CENTRAL_FUNCTION_NEW TINYINT(1) DEFAULT '0',
CENTRAL_FUNCTION_NEW_UNTIL DATETIME DEFAULT '0001-01-01 00:00:00',
LAST_MODIFIED DATETIME DEFAULT '0001-01-01 00:00:00',
ROLE VARCHAR(32) DEFAULT NULL,
PRIMARY KEY (CENTRAL_FUNCTION_ID),
UNIQUE KEY UNQ_CENTRAL_FUNCTION_KEY (CENTRAL_FUNCTION_CODE),
KEY IDX_KEY_CENTRAL_FUNCTION (CENTRAL_GROUP_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CENTRAL_REGISTRATION_ASSOCIATION'
--

CREATE TABLE CENTRAL_REG_ASSOCIATION (
CENTRAL_REG_ASSOCIATION_ID INT(11) NOT NULL,
MERCHANT_REGISTRATION_DEF_CODE INT(3) NOT NULL,
CENTRAL_GROUP_CODE VARCHAR(10) DEFAULT '',
CENTRAL_FUNCTION_CODE VARCHAR(10) DEFAULT '',
PROMOTION_CODE INT(5) DEFAULT '0',
LAST_MODIFIED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (CENTRAL_REG_ASSOCIATION_ID),
UNIQUE KEY UNQ_CENTRAL_REG_ASS_KEY (MERCHANT_REGISTRATION_DEF_CODE,CENTRAL_GROUP_CODE,CENTRAL_FUNCTION_CODE,PROMOTION_CODE),
KEY IDX_KEY_CENTRAL_FUNCTION_1 (MERCHANT_REGISTRATION_DEF_CODE,CENTRAL_GROUP_CODE),
KEY IDX_KEY_CENTRAL_FUNCTION_2 (MERCHANT_REGISTRATION_DEF_CODE,CENTRAL_FUNCTION_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CENTRAL_GROUP'
--

CREATE TABLE CENTRAL_GROUP (
CENTRAL_GROUP_ID INT(5) NOT NULL AUTO_INCREMENT,
CENTRAL_GROUP_CODE VARCHAR(10) NOT NULL DEFAULT '',
CENTRAL_GROUP_DESCRIPTION VARCHAR(40) DEFAULT NULL,
CENTRAL_GROUP_POSITION TINYINT(3) NOT NULL DEFAULT '0',
CENTRAL_GROUP_VISIBLE TINYINT(1) NOT NULL DEFAULT '0',
CENTRAL_GROUP_NEW TINYINT(1) NOT NULL DEFAULT '0',
CENTRAL_GROUP_NEW_UNTIL DATETIME DEFAULT '0001-01-01 00:00:00',
LAST_MODIFIED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (CENTRAL_GROUP_ID),
UNIQUE KEY UNQ_CENTRAL_GROUP_KEY (CENTRAL_GROUP_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------


--
-- TABLE STRUCTURE FOR TABLE 'CENTRAL_INTEGRATION_ERRORS'
--

CREATE TABLE CENTRAL_INTEGRATION_ERRORS (
CENTRAL_INTEGRATION_ERRORS_ID INT(11) NOT NULL,
MERCHANTID INT(11) NOT NULL DEFAULT '0',
CENTRAL_INTEGRATION_ERR_DESC VARCHAR(255) DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (CENTRAL_INTEGRATION_ERRORS_ID),
KEY IDX_CENTRAL_INT_ERRORS (MERCHANTID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CORE_MODULES_SERVICES'
--

CREATE TABLE CORE_MODULES_SERVICES (
CORE_MD_SERVICES_ID INT(11) NOT NULL AUTO_INCREMENT,
CORE_MD_SERVICES_CODE INT(11) NOT NULL,
CORE_MD_NAME VARCHAR(60) NOT NULL,
COUNTRY_ISO_CODE_2 CHAR(2) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT 'XX',
CORE_MD_SERVICES_SUBTYPE INT(3) NOT NULL DEFAULT '0',
CORE_MD_SERVICES_DESCRIPTION VARCHAR(100) DEFAULT NULL,
CORE_MD_SERVICES_LOGO_PATH TEXT COLLATE LATIN1_GENERAL_CI,
CORE_MD_SERVICES_POSITION TINYINT(3) DEFAULT '0',
CORE_MD_SERVICES_VISIBLE TINYINT(1) DEFAULT '0',
CORE_MD_SERVICES_NEW TINYINT(1) DEFAULT '1',
CORE_MD_SERVICES_URL VARCHAR(120) DEFAULT NULL,
CORE_MD_SERVICES_DEV_PROTOCOL VARCHAR(10) DEFAULT NULL,
CORE_MD_SERVICES_DEV_DOMAIN VARCHAR(75) DEFAULT NULL,
CORE_MD_SERVICES_DEV_PORT VARCHAR(10) DEFAULT NULL,
CORE_MD_SERVICES_DEV_ENV VARCHAR(100) DEFAULT NULL,
CORE_MD_SERVICES_PROD_PROTOCOL VARCHAR(10) DEFAULT NULL,
CORE_MD_SERVICES_PROD_DOMAIN VARCHAR(75) DEFAULT NULL,
CORE_MD_SERVICES_PROD_PORT VARCHAR(10) DEFAULT NULL,
CORE_MD_SERVICES_PROD_ENV VARCHAR(75) DEFAULT NULL,
CORE_MD_SERVICES_CONFIGURABLE TINYINT(1) DEFAULT '0',
PRIMARY KEY (CORE_MD_SERVICES_ID),
KEY IDX_CORE_MODULES_SERVICES (CORE_MD_SERVICES_CODE,COUNTRY_ISO_CODE_2,CORE_MD_NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CENTRAL_MEASURE_UNITS'
--

CREATE TABLE CENTRAL_MEASURE_UNITS (
CENTRAL_MEASURE_UNITS_ID INT(11) NOT NULL AUTO_INCREMENT,
CENTRAL_MEASURE_UNITS_TYPE INT(2) NOT NULL,
CENTRAL_MEASURE_UNITS_CODE CHAR(5) NOT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (CENTRAL_MEASURE_UNITS_ID),
KEY IDX_CENTRAL_MEASURE_UNITS_CODE (CENTRAL_MEASURE_UNITS_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CENTRAL_SEQUENCER'
--

CREATE TABLE CENTRAL_SEQUENCER (
CENTRAL_SEQUENCER_ID INT(3) NOT NULL DEFAULT '0',
CUST_BASKET_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
CUST_BASKET_ATTR_ID_NEXT_VAL INT(11) NOT NULL DEFAULT '0',
MERCHANT_CONF_ID_NEXT_VAL INT(11) NOT NULL DEFAULT '0',
MERCHANT_USER_INFO_ID_NEXT_VAL INT(11) NOT NULL DEFAULT '0',
CATEGORY_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
PRODUCT_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
PRODUCT_OPTIONS_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
PRODUCT_ATTR_ID_NEXT_VAL INT(11) NOT NULL DEFAULT '0',
PRODUCT_PRICE_ID_NEXT_VAL INT(11) NOT NULL DEFAULT '0',
GEO_ZONE_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
TAX_RATE_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
PRODUCT_OPTION_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
PRODUCT_OPT_VALUES_ID_NEXT_VAL INT(11) NOT NULL DEFAULT '0',
ORDER_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
CUSTOMER_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
ORDER_TOTAL_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
ORDER_PRODUCT_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
ORDER_PRD_PRICE_ID_NEXT_VAL INT(11) NOT NULL DEFAULT '0',
ORDER_PRODUCT_ATTR_ID_NEXT_VAL INT(11) NOT NULL DEFAULT '0',
ORDER_PRODUCT_DL_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0', 
ORDER_ACCOUNT_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
ORDER_ACCOUNT_PRD_ID_NEXT_VAL INT(11) NOT NULL DEFAULT '0',
ORDER_ACCNT_PRD_PRICE_ID_N_VAL INT(11) NOT NULL DEFAULT '0',
ORDER_ACCNT_PRD_ATTR_ID_N_VAL INT(11) NOT NULL DEFAULT '0',
PRODUCT_SPECIAL_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
DYNAMIC_LABEL_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
GATEWAY_TRX_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
REVIEW_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
MERCHANTID_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
CRA_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
CIE_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
MANUFACTURERS_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
MRD_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
MUR_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
GTGZ_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
STATUS_HIST_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
RELATIONSHIP_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
TAXCLASS_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
PORTLET_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
PAGE_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
PAGEFLOW_ID_NEXT_VALUE INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (CENTRAL_SEQUENCER_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'COUNTRIES'
--

CREATE TABLE COUNTRIES (
COUNTRIES_ID INT(11) NOT NULL AUTO_INCREMENT,
COUNTRIES_ISO_CODE_2 CHAR(2) NOT NULL DEFAULT '',
COUNTRIES_ISO_CODE_3 CHAR(3) NOT NULL DEFAULT '',
COUNTRIES_GROUP_CODE CHAR(3) DEFAULT '',
ADDRESS_FORMAT_ID INT(11) NOT NULL DEFAULT '0',
SUPPORTED TINYINT(1) NOT NULL DEFAULT '0',
PRIMARY KEY (COUNTRIES_ID),
KEY IDX_ADDRESS_FORMAT_ID_SM (ADDRESS_FORMAT_ID),
KEY IDX_ISO_2_SM (COUNTRIES_ISO_CODE_2),
KEY IDX_ISO_3_SM (COUNTRIES_ISO_CODE_3),
KEY IDX_CODE_SM (COUNTRIES_GROUP_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

CREATE TABLE COUNTRIES_DESCRIPTION (
COUNTRIES_ID INT(11) NOT NULL,
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
COUNTRIES_NAME VARCHAR(64) NOT NULL DEFAULT '',
PRIMARY KEY (COUNTRIES_ID,LANGUAGE_ID),
KEY IDX_COUNTRIES_NAME_SM (COUNTRIES_NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CURRENCIES'
--

CREATE TABLE CURRENCIES (
CURRENCIES_ID INT(11) NOT NULL AUTO_INCREMENT,
TITLE VARCHAR(32) NOT NULL DEFAULT '',
CODE CHAR(3) NOT NULL DEFAULT '',
SYMBOL VARCHAR(10) DEFAULT NULL,
SUFFIX VARCHAR(10) DEFAULT NULL,
DECIMAL_POINT CHAR(1) DEFAULT NULL,
THOUSANDS_POINT CHAR(1) DEFAULT NULL,
DECIMAL_PLACES CHAR(1) DEFAULT NULL,
VALUE FLOAT(13,8) DEFAULT NULL,
LAST_UPDATED DATETIME DEFAULT NULL,
SUPPORTED TINYINT(1) NOT NULL DEFAULT '0',
PRIMARY KEY (CURRENCIES_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CUSTOMERS'
--

CREATE TABLE CUSTOMERS (
CUSTOMERS_ID INT(11) NOT NULL,
CUSTOMERS_GENDER CHAR(1) DEFAULT '',
CUSTOMERS_FIRSTNAME VARCHAR(32) NOT NULL DEFAULT '',
CUSTOMERS_LASTNAME VARCHAR(32) NOT NULL DEFAULT '',
CUSTOMERS_DOB DATETIME DEFAULT '0001-01-01 00:00:00',
CUSTOMERS_EMAIL_ADDRESS VARCHAR(96) NOT NULL DEFAULT '',
CUSTOMERS_NICK VARCHAR(96) DEFAULT '',
CUSTOMERS_TELEPHONE VARCHAR(32) NOT NULL DEFAULT '',
CUSTOMERS_ADDRESS VARCHAR(256) NOT NULL DEFAULT '',
CUSTOMERS_POSTALCODE VARCHAR(20) NOT NULL DEFAULT '',
CUSTOMERS_CITY VARCHAR(100) NOT NULL DEFAULT '',
CUSTOMERS_COMPANY VARCHAR(100) DEFAULT '' NULL,
CUSTOMERS_STATE VARCHAR(100) DEFAULT '',
CUSTOMERS_ZONE INT(11) NOT NULL,
CUSTOMERS_COUNTRY INT(11) NOT NULL,
CUSTOMERS_BILLING_FIRSTNAME VARCHAR(32) NULL,
CUSTOMERS_BILLING_LASTNAME VARCHAR(32) NULL,
CUSTOMERS_BILLING_COMPANY VARCHAR(100) NULL,
CUSTOMERS_BILLING_ADDRESS VARCHAR(256) NULL DEFAULT '',
CUSTOMERS_BILLING_POSTALCODE VARCHAR(20) NULL DEFAULT '',
CUSTOMERS_BILLING_CITY VARCHAR(100) NULL DEFAULT '',
CUSTOMERS_BILLING_STATE VARCHAR(100) NULL DEFAULT '',
CUSTOMERS_BILLING_ZONE INT(11) NULL DEFAULT 0,
CUSTOMERS_BILLING_COUNTRY INT(11) NULL DEFAULT 0,
CUSTOMERS_FAX VARCHAR(32) DEFAULT NULL,
CUSTOMERS_PASSWORD VARCHAR(40) DEFAULT '',
CUSTOMERS_NEWSLETTER CHAR(1) DEFAULT NULL,
CUSTOMERS_GROUP_PRICING INT(11) DEFAULT '0',
CUSTOMERS_EMAIL_FORMAT VARCHAR(4) DEFAULT 'TEXT',
CUSTOMERS_AUTHORIZATION INT(1) DEFAULT '0',
CUSTOMERS_REFERRAL VARCHAR(32) DEFAULT '',
CUSTOMERS_ANONYMOUS TINYINT(1) UNSIGNED DEFAULT '0',
CUSTOMERS_LANG VARCHAR(2) NOT NULL DEFAULT 'EN',
MERCHANTID INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (CUSTOMERS_ID),
KEY IDX_EMAIL_ADDRESS_SM (CUSTOMERS_EMAIL_ADDRESS),
KEY IDX_REFERRAL_SM (CUSTOMERS_REFERRAL(10)),
KEY IDX_GRP_PRICING_SM (CUSTOMERS_GROUP_PRICING),
KEY IDX_NICK_SM (CUSTOMERS_NICK),
KEY IDX_LAST_NAME_SM (CUSTOMERS_LASTNAME),
KEY IDX_NEWSLETTER_SM (CUSTOMERS_NEWSLETTER),
KEY IDX_MID_SM_CUST (MERCHANTID),
KEY IDX_COMPANY_SM (MERCHANTID,CUSTOMERS_COMPANY(25)),
KEY IDX_COUNTRY_SM (CUSTOMERS_COUNTRY)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CUSTOMERS_BASKET'
--

CREATE TABLE CUSTOMERS_BASKET (
CUSTOMERS_BASKET_ID INT(11) NOT NULL,
CUSTOMERS_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_ID TINYTEXT NOT NULL,
CUSTOMERS_BASKET_QUANTITY INT(11) NOT NULL DEFAULT '0',
FINAL_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
CUSTOMERS_BASKET_DATE_ADDED VARCHAR(8) DEFAULT NULL,
MERCHANTID INT(11) DEFAULT '0',
PRIMARY KEY (CUSTOMERS_BASKET_ID),
KEY IDX_CUST_ID_BASK_SM (CUSTOMERS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CUSTOMERS_BASKET_ATTRIBUTES'
--

CREATE TABLE CUSTOMERS_BASKET_ATTRIBUTES (
CUSTOMERS_BASKET_ATTRIBUTES_ID INT(11) NOT NULL,
CUSTOMERS_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_ID TINYTEXT NOT NULL,
PRODUCTS_OPTIONS_ID VARCHAR(64) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS_VALUE_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS_VALUE_TEXT VARCHAR(255) CHARACTER SET UTF8,
PRODUCTS_OPTIONS_SORT_ORDER TEXT NOT NULL,
MERCHANTID INT(11) DEFAULT '0',
PRIMARY KEY (CUSTOMERS_BASKET_ATTRIBUTES_ID),
KEY IDX_CUST_ID_PROD_ID_SM (CUSTOMERS_ID,PRODUCTS_ID(36))
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CUSTOMERS_INFO'
--

CREATE TABLE CUSTOMERS_INFO (
CUSTOMERS_INFO_ID INT(11) NOT NULL DEFAULT '0',
CUSTOMERS_INFO_DT_LAST_LOGON DATETIME DEFAULT NULL,
CUSTOMERS_INFO_NUMBER_LOGONS INT(5) DEFAULT NULL,
CUSTOMERS_INFO_DT_ACC_CREATED DATETIME DEFAULT NULL,
CUSTOMERS_INFO_DT_ACC_MODIFIED DATETIME DEFAULT NULL,
GLOBAL_PRODUCT_NOTIFICATIONS INT(1) DEFAULT '0',
PRIMARY KEY (CUSTOMERS_INFO_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'CUSTOMERS_WISHLIST'
--

CREATE TABLE CUSTOMERS_WISHLIST (
PRODUCTS_ID INT(13) NOT NULL DEFAULT '0',
CUSTOMERS_ID INT(13) NOT NULL DEFAULT '0',
PRODUCTS_MODEL VARCHAR(13) DEFAULT NULL,
PRODUCTS_NAME VARCHAR(64) NOT NULL DEFAULT '',
PRODUCTS_PRICE DECIMAL(8,2) NOT NULL DEFAULT '0.00',
FINAL_PRICE DECIMAL(8,2) NOT NULL DEFAULT '0.00',
PRODUCTS_QUANTITY INT(2) NOT NULL DEFAULT '0',
WISHLIST_NAME VARCHAR(64) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'FILES_HISTORY'
--

CREATE TABLE FILES_HISTORY (
MERCHANTID INT(11) NOT NULL DEFAULT '0',
FILEID INT(11) NOT NULL,
FILESIZE INT(11) NOT NULL,
DATE_ADDED DATETIME NOT NULL,
DATE_DELETED DATETIME DEFAULT NULL,
ACCOUNTED_DATE DATETIME DEFAULT NULL,
DOWNLOAD_COUNT INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (MERCHANTID,FILEID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'GEO_ZONES_TAX_TEMPLATE'
--

CREATE TABLE GEO_ZONES_TAX_TEMPLATE (
GEO_ZONE_ID INT(11) NOT NULL AUTO_INCREMENT,
GEO_ZONE_NAME VARCHAR(32) NOT NULL DEFAULT '',
GEO_ZONE_DESCRIPTION VARCHAR(255) DEFAULT '',
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
SCHEMEID INT(3) NOT NULL DEFAULT '0',
PRIMARY KEY (GEO_ZONE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'LANGUAGES'
--

CREATE TABLE LANGUAGES (
LANGUAGES_ID INT(11) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(32) NOT NULL DEFAULT '',
CODE CHAR(2) NOT NULL DEFAULT '',
IMAGE VARCHAR(64) DEFAULT NULL,
DIRECTORY VARCHAR(32) DEFAULT NULL,
SORT_ORDER INT(3) DEFAULT NULL,
PRIMARY KEY (LANGUAGES_ID),
KEY IDX_LANGUAGES_NAME_SM (NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MANUFACTURERS'
--

CREATE TABLE MANUFACTURERS (
MANUFACTURERS_ID INT(11) NOT NULL,
MANUFACTURERS_NAME VARCHAR(32) NOT NULL DEFAULT '',
MANUFACTURERS_IMAGE VARCHAR(64) DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT NULL,
LAST_MODIFIED DATETIME DEFAULT NULL,
PRIMARY KEY (MANUFACTURERS_ID),
KEY IDX_MFG_NAME_SM (MANUFACTURERS_NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

--
-- DUMPING DATA FOR TABLE 'MANUFACTURERS'
--


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MANUFACTURERS_INFO'
--

CREATE TABLE MANUFACTURERS_INFO (
MANUFACTURERS_ID INT(11) NOT NULL DEFAULT '0',
LANGUAGES_ID INT(11) NOT NULL DEFAULT '0',
MANUFACTURERS_URL VARCHAR(255) NOT NULL DEFAULT '',
URL_CLICKED INT(5) NOT NULL DEFAULT '0',
DATE_LAST_CLICK DATETIME DEFAULT NULL,
PRIMARY KEY (MANUFACTURERS_ID,LANGUAGES_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MERCHANT_CONFIGURATION'
--

CREATE TABLE MERCHANT_CONFIGURATION (
CONFIGURATION_ID INT(11) NOT NULL,
MERCHANT_ID INT(11) NOT NULL,
CONFIGURATION_KEY VARCHAR(255) NOT NULL DEFAULT '',
CONFIGURATION_VALUE TEXT COLLATE LATIN1_GENERAL_CI,
CONFIGURATION_VALUE1 TEXT COLLATE LATIN1_GENERAL_CI,
CONFIGURATION_VALUE2 TEXT COLLATE LATIN1_GENERAL_CI,
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
CONFIGURATION_MODULE VARCHAR(60) DEFAULT '',
SORT_ORDER INT(3) DEFAULT 0,
PRIMARY KEY (CONFIGURATION_ID),
KEY IDX_KEY_VALUE2_MERCH (MERCHANT_ID,CONFIGURATION_KEY(17)),
KEY IDX_KEY_VALUE1_MERCH (MERCHANT_ID),
KEY IDX_KEY_MODULE_MERCH (CONFIGURATION_MODULE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

--
-- TABLE STRUCTURE FOR TABLE 'GEO_ZONES'
--

CREATE TABLE GEO_ZONES (
GEO_ZONE_ID INT(11) NOT NULL,
MERCHANTID INT(11) NOT NULL DEFAULT '0',
GEO_ZONE_NAME VARCHAR(32) NOT NULL DEFAULT '',
GEO_ZONE_DESCRIPTION VARCHAR(255) DEFAULT '',
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (GEO_ZONE_ID),
KEY IDX_GEO_ZONES_MERCH_ID_SM (MERCHANTID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MERCHANT_ID'
--

CREATE TABLE MERCHANT_ID (
MERCHANTID INT(11) NOT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (MERCHANTID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MERCHANT_PAYMENT_GATEWAY_TRX'
--

CREATE TABLE MERCHANT_PAYMENT_GATEWAY_TRX (
MERCHANT_PAYMENT_GW_ID INT(11) NOT NULL,
MERCHANTID INT(11) NOT NULL DEFAULT '0',
CUSTOMERID INT(11) NOT NULL,
ORDERS_ID INT(11) NOT NULL,
MERCHANT_PAYMENT_GW_METHOD VARCHAR(50) NOT NULL DEFAULT '',
MERCHANT_PAYMENT_GW_ORDERID VARCHAR(100) NOT NULL DEFAULT '',
MERCHANT_PAYMENT_GW_RESPCODE VARCHAR(25) DEFAULT NULL,
MERCHANT_PAYMENT_GW_TRXID VARCHAR(100) NOT NULL DEFAULT '',
MERCHANT_PAYMENT_GW_AUTHTYPE VARCHAR(25) NOT NULL DEFAULT '',
MERCHANT_PAYMENT_GW_SENT TEXT NOT NULL,
MERCHANT_PAYMENT_GW_RECEIVED TEXT NOT NULL,
MERCHANT_PAYMENT_GW_SESSION VARCHAR(255) DEFAULT '',
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
AMOUNT DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
PRIMARY KEY (MERCHANT_PAYMENT_GW_ID),
KEY IDX_PAYMENT_GATEWAY_MERCH (MERCHANTID),
KEY IDX_PAYMENT_GATEWAY_TRX_CLIENT (MERCHANTID,CUSTOMERID),
KEY IDX_PAYMENT_GATEWAY_TRX_GORDER (MERCHANTID,MERCHANT_PAYMENT_GW_ORDERID),
KEY IDX_PAYMENT_GATEWAY_TRX_ORDER (MERCHANTID,ORDERS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------


--
-- TABLE STRUCTURE FOR TABLE 'MERCHANT_REGISTRATION'
--

CREATE TABLE MERCHANT_REGISTRATION (
MERCHANTID INT(11) NOT NULL DEFAULT '0',
MERCHANT_REGISTRATION_DEF_CODE INT(3) NOT NULL,
PROMO_CODE INT(5) NOT NULL DEFAULT '0',
CC_TYPE VARCHAR(20) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
CC_OWNER VARCHAR(64) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
CC_NUMBER VARCHAR(100) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
CC_EXPIRES VARCHAR(4) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
CC_CVV BLOB,
LAST_MODIFIED DATETIME DEFAULT NULL,
PROMO_CODE_EXPIRY DATETIME DEFAULT '0001-01-01 00:00:00',
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (MERCHANTID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MERCHANT_REGISTRATION_DEF'
--

CREATE TABLE MERCHANT_REGISTRATION_DEF (
MERCHANT_REG_DEF_ID INT(5) NOT NULL,
MERCHANT_REG_DEF_CODE INT(3) NOT NULL,
MERCHANT_REG_DEF_TYPE INT(3) NOT NULL DEFAULT '0',
MERCHANT_REG_DEF_ONE_TIME DECIMAL(6,4) NOT NULL DEFAULT '0.0000',
MERCHANT_REG_DEF_MONTHLY DECIMAL(6,4) NOT NULL DEFAULT '0.0000',
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (MERCHANT_REG_DEF_ID),
KEY IDX_MERCHANT_REGISTRATION_DEF (MERCHANT_REG_DEF_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MERCHANT_STORE'
--

CREATE TABLE MERCHANT_STORE (
MERCHANTID INT(11) NOT NULL DEFAULT '0',
STORENAME VARCHAR(40) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
COUNTRY INT(5) NOT NULL DEFAULT '223',
ZONE VARCHAR(64) COLLATE UTF8_UNICODE_CI NOT NULL,
STORESTATEPROVINCE VARCHAR(64) COLLATE UTF8_UNICODE_CI DEFAULT '',
CURRENCY VARCHAR(6) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
BGCOLORCODE INT(3) DEFAULT '1',
STORELOGO VARCHAR(255) COLLATE UTF8_UNICODE_CI DEFAULT '',
STOREBANNER VARCHAR(255) COLLATE UTF8_UNICODE_CI DEFAULT '',
STOREPHONE VARCHAR(15) COLLATE UTF8_UNICODE_CI DEFAULT '',
STOREEMAILADDRESS VARCHAR(96) COLLATE UTF8_UNICODE_CI DEFAULT '',
CONTINUESHOPPINGURL VARCHAR(100) COLLATE UTF8_UNICODE_CI DEFAULT '',
STOREADDRESS VARCHAR(100) COLLATE UTF8_UNICODE_CI DEFAULT '',
STORECITY VARCHAR(60) COLLATE UTF8_UNICODE_CI DEFAULT '',
STOREPOSTALCODE VARCHAR(15) COLLATE UTF8_UNICODE_CI DEFAULT '',
SUPPORTEDLANGUAGES VARCHAR(20) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
WEIGHTUNITCODE CHAR(2) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT 'LB',
SEIZEUNITCODE CHAR(2) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT 'IN',
LAST_MODIFIED DATETIME DEFAULT '0001-01-01 00:00:00',
IN_BUSINESS_SINCE DATETIME,
TEMPLATE_MODULE VARCHAR(64) DEFAULT 'BASETEMPLATE',
INVOICE_MODULE VARCHAR(64) NULL,
USE_CACHE TINYINT(1) NOT NULL DEFAULT '1',
DEFAULTLANG CHAR(2) COLLATE UTF8_UNICODE_CI,
DOMAINNAME VARCHAR(255) DEFAULT 'localhost',
PRIMARY KEY (MERCHANTID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'TAX_RATES'
--

CREATE TABLE TAX_RATES (
TAX_RATES_ID INT(11) NOT NULL,
MERCHANTID INT(11) NOT NULL DEFAULT '0',
TAX_ZONE_ID INT(11) NOT NULL DEFAULT '0',
TAX_CLASS_ID INT(11) NOT NULL DEFAULT '0',
TAX_PRIORITY INT(5) DEFAULT '1',
TAX_RATE DECIMAL(7,4) NOT NULL DEFAULT '0.0000',
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
PIGGYBACK TINYINT(1) DEFAULT '0',
PRIMARY KEY (TAX_RATES_ID),
KEY IDX_MERCH_TAX_MERCH_ID_SM (MERCHANTID),
KEY IDX_MERCH_TAX_ZONE_ID_SM (TAX_ZONE_ID),
KEY IDX_MERCH_TAX_CLASS_ID_SM (TAX_CLASS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

CREATE TABLE TAX_RATES_DESCRIPTION (
TAX_RATES_ID INT(11) NOT NULL,
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
TAX_DESCRIPTION VARCHAR(255) NOT NULL DEFAULT '',
PRIMARY KEY (TAX_RATES_ID,LANGUAGE_ID),
KEY IDX_MERCH_TAX_RATES_DESC_ID (TAX_RATES_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MERCHANT_USER_INFORMATION'
--

CREATE TABLE MERCHANT_USER_INFORMATION (
MERCHANT_USER_ID INT(11) NOT NULL,
ADMIN_NAME VARCHAR(32) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
ADMIN_EMAIL VARCHAR(96) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
ADMIN_PASS VARCHAR(40) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
TOKEN VARCHAR(40) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
USERFNAME VARCHAR(40) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
USERLNAME VARCHAR(40) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
USERADDRESS VARCHAR(100) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
USERCITY VARCHAR(40) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
USERPOSTALCODE VARCHAR(15) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
USERSTATE VARCHAR(100) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
USERCOUNTRYCODE INT(5) NOT NULL,
USERPHONE VARCHAR(15) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
USERLANG VARCHAR(2) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT 'EN',
STATUS INT(3) NOT NULL DEFAULT '0',
LAST_MODIFIED DATETIME DEFAULT '0001-01-01 00:00:00',
MERCHANTID INT(11) DEFAULT NULL DEFAULT '0',
PRIMARY KEY (MERCHANT_USER_ID),
SECURITY_QUESTION_1 VARCHAR(64) DEFAULT NULL,
SECURITY_QUESTION_2 VARCHAR(64) DEFAULT NULL,
SECURITY_QUESTION_3 VARCHAR(64) DEFAULT NULL,
SECURITY_ANSWER_1 VARCHAR(64) DEFAULT NULL,
SECURITY_ANSWER_2 VARCHAR(64) DEFAULT NULL,
SECURITY_ANSWER_3 VARCHAR(64) DEFAULT NULL,
UNIQUE KEY UNQ_MERCH_INF_KEY (ADMIN_EMAIL),
KEY IDX_KEY_ADMIN_NAME_MERCH (ADMIN_NAME),
KEY IDX_KEY_ADMIN_PASS_MERCH (ADMIN_PASS),
KEY IDX_KEY_MERCHANTID_MERCH (MERCHANTID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MERCHANT_USER_ROLE'
--

CREATE TABLE MERCHANT_USER_ROLE (
MERCHANT_USER_ROLE_ID INT(11) NOT NULL,
ADMIN_NAME VARCHAR(32) COLLATE UTF8_UNICODE_CI NOT NULL,
ROLE_CODE VARCHAR(10) COLLATE UTF8_UNICODE_CI NOT NULL,
PRIMARY KEY (MERCHANT_USER_ROLE_ID),
KEY IDX_KEY_ADMIN_NAME (ADMIN_NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MERCHANT_USER_ROLE_DEF'
--

CREATE TABLE MERCHANT_USER_ROLE_DEF (
ROLEID INT(11) NOT NULL AUTO_INCREMENT,
ROLE_CODE VARCHAR(10) COLLATE UTF8_UNICODE_CI NOT NULL,
ROLE_DESCRIPTION VARCHAR(255) COLLATE UTF8_UNICODE_CI DEFAULT NULL,
PRIMARY KEY (ROLEID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'ZONES_TO_GEO_ZONES'
--

CREATE TABLE ZONES_TO_GEO_ZONES (
ASSOCIATION_ID INT(11) NOT NULL,
MERCHANTID INT(11) NOT NULL DEFAULT '0',
ZONE_COUNTRY_ID INT(11) NOT NULL DEFAULT '0',
ZONE_ID INT(11) DEFAULT NULL,
GEO_ZONE_ID INT(11) DEFAULT NULL,
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (ASSOCIATION_ID),
KEY IDX_MERCH_ZONES_SM (GEO_ZONE_ID,ZONE_COUNTRY_ID,ZONE_ID,MERCHANTID),
KEY IDX_MERCH_ZONES_MERCHANT_SM (MERCHANTID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'MODULE_CONFIGURATION'
--

CREATE TABLE MODULE_CONFIGURATION (
CONFIGURATION_MODULE VARCHAR(60) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
CONFIGURATION_KEY VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT '',
COUNTRY_ISO_CODE_2 CHAR(2) COLLATE UTF8_UNICODE_CI NOT NULL DEFAULT 'XX',
CONFIGURATION_VALUE TEXT COLLATE UTF8_UNICODE_CI,
PRIMARY KEY (CONFIGURATION_MODULE,CONFIGURATION_KEY,COUNTRY_ISO_CODE_2)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'ORDERS'
--

CREATE TABLE ORDERS (
ORDERS_ID INT(11) NOT NULL,
CUSTOMERS_ID INT(11) NOT NULL DEFAULT '0',
CUSTOMERS_NAME VARCHAR(64) NOT NULL DEFAULT '',
CUSTOMERS_COMPANY VARCHAR(32) DEFAULT NULL,
CUSTOMERS_STREET_ADDRESS VARCHAR(64) NOT NULL DEFAULT '',
CUSTOMERS_SUBURB VARCHAR(32) DEFAULT NULL,
CUSTOMERS_CITY VARCHAR(32) NOT NULL DEFAULT '',
CUSTOMERS_POSTCODE VARCHAR(10) NOT NULL DEFAULT '',
CUSTOMERS_STATE VARCHAR(32) DEFAULT NULL,
CUSTOMERS_COUNTRY VARCHAR(32) NOT NULL DEFAULT '',
CUSTOMERS_TELEPHONE VARCHAR(32) NOT NULL DEFAULT '',
CUSTOMERS_EMAIL_ADDRESS VARCHAR(96) NOT NULL DEFAULT '',
CUSTOMERS_ADDRESS_FORMAT_ID INT(5) DEFAULT '0',
DELIVERY_NAME VARCHAR(64) DEFAULT '',
DELIVERY_COMPANY VARCHAR(32) DEFAULT NULL,
DELIVERY_STREET_ADDRESS VARCHAR(64) DEFAULT '',
DELIVERY_SUBURB VARCHAR(32) DEFAULT NULL,
DELIVERY_CITY VARCHAR(32) DEFAULT '',
DELIVERY_POSTCODE VARCHAR(10) DEFAULT '',
DELIVERY_STATE VARCHAR(32) DEFAULT NULL,
DELIVERY_COUNTRY VARCHAR(32) DEFAULT '',
DELIVERY_ADDRESS_FORMAT_ID INT(5) DEFAULT '0',
BILLING_NAME VARCHAR(64) DEFAULT '',
BILLING_COMPANY VARCHAR(32) DEFAULT NULL,
BILLING_STREET_ADDRESS VARCHAR(64) DEFAULT '',
BILLING_SUBURB VARCHAR(32) DEFAULT NULL,
BILLING_CITY VARCHAR(32) DEFAULT '',
BILLING_POSTCODE VARCHAR(10) DEFAULT '',
BILLING_STATE VARCHAR(32) DEFAULT NULL,
BILLING_COUNTRY VARCHAR(32) DEFAULT '',
BILLING_ADDRESS_FORMAT_ID INT(5) DEFAULT '0',
PAYMENT_METHOD VARCHAR(128) DEFAULT '',
PAYMENT_MODULE_CODE VARCHAR(60) DEFAULT '',
SHIPPING_METHOD VARCHAR(128) DEFAULT '',
SHIPPING_MODULE_CODE VARCHAR(60) DEFAULT '',
COUPON_CODE VARCHAR(32) DEFAULT '',
CARD_TYPE VARCHAR(20) DEFAULT NULL,
CC_OWNER VARCHAR(64) DEFAULT NULL,
CC_NUMBER VARCHAR(32) DEFAULT NULL,
CC_EXPIRES VARCHAR(4) DEFAULT NULL,
CC_CVV VARCHAR(10) DEFAULT NULL,
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_PURCHASED DATETIME DEFAULT NULL,
ORDERS_STATUS INT(5) DEFAULT '0',
ORDERS_DATE_FINISHED DATETIME DEFAULT NULL,
CURRENCY CHAR(3) DEFAULT NULL,
CURRENCY_VALUE DECIMAL(14,6) DEFAULT NULL,
ORDER_TOTAL DECIMAL(14,2) DEFAULT NULL,
ORDER_TAX DECIMAL(14,2) DEFAULT NULL,
IP_ADDRESS VARCHAR(96) DEFAULT '',
MERCHANTID INT(11) DEFAULT '0',
CHANNEL INT(3) DEFAULT '0',
DISPLAY_INVOICE_PAYMENTS TINYINT(1) NOT NULL DEFAULT '0',
PRIMARY KEY (ORDERS_ID),
KEY IDX_STATUS_ORDERS_CUST_SM (ORDERS_STATUS,ORDERS_ID,CUSTOMERS_ID),
KEY IDX_DATE_PURCHASED_SM (DATE_PURCHASED),
KEY IDX_MID_SM_ORDERS (MERCHANTID),
KEY IDX_CHANEL_SM (MERCHANTID,CHANNEL),
KEY IDX_CUST_ORDER_SM (ORDERS_ID,CUSTOMERS_ID,MERCHANTID),
KEY IDX_CUSTOMER_NAME (CUSTOMERS_NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'ORDERS_PRODUCTS'
--

CREATE TABLE ORDERS_PRODUCTS (
ORDERS_PRODUCTS_ID INT(11) NOT NULL,
ORDERS_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_MODEL VARCHAR(32) DEFAULT NULL,
PRODUCTS_NAME VARCHAR(64) NOT NULL DEFAULT '',
PRODUCTS_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
FINAL_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
PRODUCTS_TAX DECIMAL(7,4) NOT NULL DEFAULT '0.0000',
PRODUCTS_QUANTITY INT(11) NOT NULL DEFAULT '0',
ONETIME_CHARGES DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
PRODUCT_IS_FREE TINYINT(1) NOT NULL DEFAULT '0',
PRODUCT_SPECIAL_NEW_PRICE DECIMAL(15,4) NULL,
PRODUCT_SPECIAL_DATE_AVAILABLE DATETIME DEFAULT NULL,
PRODUCT_SPECIAL_DATE_EXPIRE DATETIME DEFAULT NULL,
ORIGINAL_PRODUCT_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
SOLD_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000', 
PRIMARY KEY (ORDERS_PRODUCTS_ID),
KEY IDX_ORDERS_PRD_ID_SM (ORDERS_ID),
KEY IDX_ORDERS_ID_PRODID_SM (ORDERS_ID,PRODUCTS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


--
-- TABLE STRUCTURE FOR TABLE 'ORDERS_PRODUCTS_PRICES'
--

CREATE TABLE ORDERS_PRODUCTS_PRICES (
ORDERS_PRODUCTS_PRICES INT(11) NOT NULL,
ORDERS_ID INT(11) NOT NULL DEFAULT '0',
ORDERS_PRODUCTS_ID INT(11) NOT NULL DEFAULT '0',
PRODUCT_PRICE_TYPE_ID INT(3) NOT NULL DEFAULT '0',
PRODUCT_PRICE_MODULE_NAME VARCHAR(64) NOT NULL,
PRODUCT_PRICE_NAME VARCHAR(255) CHARACTER SET UTF8,
PRODUCT_PRICE_AMOUNT DECIMAL(15,2) NOT NULL,
DEFAULT_PRICE TINYINT(1) NOT NULL DEFAULT '1',
PRODUCT_HAS_TAX TINYINT(1) NOT NULL DEFAULT '0',
PRIMARY KEY (ORDERS_PRODUCTS_PRICES),
KEY IDX_ORDERS_PRD_PR_ID_SM (ORDERS_ID),
KEY IDX_O_PROD_PRICES_ID_SM (ORDERS_ID,ORDERS_PRODUCTS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


CREATE TABLE ORDERS_PRODUCTS_PRICES_SPECIAL (
ORDERS_PRODUCTS_PRICES INT(11) NOT NULL,
SPECIALS_NEW_PRODUCTS_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
ORIGINAL_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
ORDERS_PRODUCTS_SPECIAL_ST_DT DATETIME NULL,
ORDERS_PRODUCTS_SPECIAL_END_DT DATETIME NULL,
ORDERS_PRODUCTS_SPECIAL_DAYS INT(3) NULL, 
PRIMARY KEY (ORDERS_PRODUCTS_PRICES)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



--
-- TABLE STRUCTURE FOR TABLE 'ORDERS_PRODUCTS_ATTRIBUTES'
--

CREATE TABLE ORDERS_PRODUCTS_ATTRIBUTES (
ORDERS_PRODUCTS_ATTRIBUTES_ID INT(11) NOT NULL,
ORDERS_ID INT(11) NOT NULL DEFAULT '0',
ORDERS_PRODUCTS_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS VARCHAR(32) DEFAULT '',
PRODUCTS_OPTIONS_VALUES VARCHAR(256) CHARACTER SET UTF8 NOT NULL,
OPTIONS_VALUES_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
PRODUCT_ATTRIBUTE_IS_FREE TINYINT(1) NOT NULL DEFAULT '0',
PRODUCTS_ATTRIBUTES_WEIGHT DECIMAL(15,4) DEFAULT '0.0000',
PRODUCTS_OPTIONS_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS_VALUES_ID INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (ORDERS_PRODUCTS_ATTRIBUTES_ID),
KEY IDX_PROD_ID_SM (ORDERS_PRODUCTS_ID),
KEY IDX_ORDERS_PRD_ATTR_ID_SM (ORDERS_ID),
KEY IDX_O_PROD_ATTRS_ID_SM (ORDERS_ID,ORDERS_PRODUCTS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'ORDERS_PRODUCTS_DOWNLOAD'
--

CREATE TABLE ORDERS_PRODUCTS_DOWNLOAD (
ORDERS_PRODUCTS_DOWNLOAD_ID INT(11) NOT NULL,
ORDERS_ID INT(11) NOT NULL DEFAULT '0',
ORDERS_PRODUCTS_ID INT(11) NOT NULL DEFAULT '0',
ORDERS_PRODUCTS_FILENAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL DEFAULT '',
DOWNLOAD_MAXDAYS INT(2) NOT NULL DEFAULT '0',
DOWNLOAD_COUNT INT(2) NOT NULL DEFAULT '0',
FILE_ID INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (ORDERS_PRODUCTS_DOWNLOAD_ID),
KEY IDX_ORDERS_PRD_DWL_ID_SM (ORDERS_ID),
KEY IDX_ORDERS_PRODUCTS_ID_SM (ORDERS_PRODUCTS_ID),
KEY IDX_FILE_ID (FILE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'ORDERS_STATUS'
--

CREATE TABLE ORDERS_STATUS (
ORDERS_STATUS_ID INT(11) NOT NULL DEFAULT '0',
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
ORDERS_STATUS_NAME VARCHAR(32) NOT NULL DEFAULT '',
PRIMARY KEY (ORDERS_STATUS_ID,LANGUAGE_ID),
KEY IDX_ORDERS_STATUS_NAME_SM (ORDERS_STATUS_NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------


CREATE TABLE ORDERS_STATUS_HISTORY (
ORDERS_STATUS_HISTORY_ID INT(11) NOT NULL,
ORDERS_ID INT(11) NOT NULL DEFAULT '0',
ORDERS_STATUS_ID INT(5) NOT NULL DEFAULT '0',
DATE_ADDED DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
CUSTOMER_NOTIFIED INT(1) DEFAULT '0',
COMMENTS TEXT COLLATE UTF8_UNICODE_CI,
PRIMARY KEY (ORDERS_STATUS_HISTORY_ID),
KEY IDX_ORDERS_STAT_HIST_ID_SM (ORDERS_ID),
KEY IDX_ORDERS_ID_STATUS_ID_SM (ORDERS_ID,ORDERS_STATUS_ID)
) ENGINE=MYISAM DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'ORDERS_TOTAL'
--

CREATE TABLE ORDERS_TOTAL (
ORDERS_TOTAL_ID INT(11) NOT NULL,
ORDERS_ID INT(11) NOT NULL DEFAULT '0',
TITLE VARCHAR(255) NOT NULL DEFAULT '',
TEXT VARCHAR(255) NOT NULL DEFAULT '',
VALUE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
MODULE VARCHAR(50) NOT NULL DEFAULT '',
SORT_ORDER INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (ORDERS_TOTAL_ID),
KEY IDX_OT_ORDERS_ID_SM (ORDERS_ID),
KEY IDX_OT_MODULE_SM (MODULE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------


--
-- TABLE STRUCTURE FOR TABLE 'OFFSYSTEM_PENDING_ORDERS'
--

CREATE TABLE OFFSYSTEM_PENDING_ORDERS (
OFFSYSTEM_PENDING_ORDER_ID INT(11) NOT NULL,
DATE_ADDED DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
PAYER_EMAIL VARCHAR(100) NOT NULL DEFAULT '',
TRANSACTION_ID VARCHAR(100) DEFAULT '',
ORDER_ID INT(11) NOT NULL DEFAULT '0',
OFFSYSTEM_MODULE VARCHAR(255) DEFAULT '',
MERCHANT_ID INT(11) DEFAULT '0',
PRIMARY KEY (OFFSYSTEM_PENDING_ORDER_ID),
KEY IDX_OFFSYSTEM_PENDING_MID (MERCHANT_ID),
KEY IDX_OFFSYSTEM_PENDING_PPK (TRANSACTION_ID,PAYER_EMAIL)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'OFFSYSTEM_NOTIFICATION_ORDERS'
--

CREATE TABLE OFFSYSTEM_NOTIFICATION_ORDERS (
OFFSYSTEM_NOTIF_ORDER_ID INT(11) NOT NULL,
OFFSYSTEM_PENDING_ORDER_ID INT(11) UNSIGNED NOT NULL,
PAYER_EMAIL VARCHAR(255) NOT NULL DEFAULT '',
DATE_RECEIVED DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
OFFSYSTEM_MODULE VARCHAR(255) NOT NULL DEFAULT '',
MERCHANT_ID INT(11) DEFAULT '0',
OFFSYSTEM_STATUS INT(5) DEFAULT '0',
OFFSYSTEM_DETAILS TEXT COLLATE LATIN1_GENERAL_CI,
PRIMARY KEY (OFFSYSTEM_NOTIF_ORDER_ID),
KEY IDX_OFFSYSTEM_NOTIFICATION_MID (MERCHANT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS'
--

CREATE TABLE PRODUCTS (
PRODUCTS_ID INT(11) NOT NULL,
PRODUCTS_TYPE INT(11) NOT NULL DEFAULT '1',
PRODUCTS_QUANTITY INT(11) NOT NULL DEFAULT '0',
PRODUCTS_MODEL VARCHAR(32) DEFAULT NULL,
PRODUCTS_IMAGE VARCHAR(64) DEFAULT NULL,
PRODUCTS_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
PRODUCTS_VIRTUAL TINYINT(1) DEFAULT '0',
PRODUCTS_DATE_ADDED DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
PRODUCTS_LAST_MODIFIED DATETIME DEFAULT NULL,
PRODUCTS_DATE_AVAILABLE DATETIME DEFAULT NULL,
PRODUCTS_WEIGHT DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
PRODUCTS_STATUS TINYINT(1) DEFAULT '0',
PRODUCTS_FEATURED TINYINT(1) DEFAULT '0',
PRODUCTS_TAX_CLASS_ID INT(11) NOT NULL DEFAULT '0',
MANUFACTURERS_ID INT(11) DEFAULT NULL,
PRODUCTS_ORDERED INT(11) NOT NULL DEFAULT '0',
PRODUCTS_QUANTITY_ORDER_MIN INT(11) NOT NULL DEFAULT '1',
PRODUCTS_QUANTITY_ORDER_UNITS INT(11) NOT NULL DEFAULT '1',
PRODUCT_IS_FREE TINYINT(1) DEFAULT '0',
PRODUCT_IS_CALL TINYINT(1) DEFAULT '0',
PRODUCT_IS_ALWAYS_FREE_SHP TINYINT(1) DEFAULT '0',
PRODUCTS_QUANTITY_ORDER_MAX INT(11) NOT NULL DEFAULT '0',
PRODUCTS_SORT_ORDER INT(11) NOT NULL DEFAULT '0',
MASTER_CATEGORIES_ID INT(11) NOT NULL DEFAULT '0',
MERCHANTID INT(11) DEFAULT '0',
PRODUCTS_LENGTH DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
PRODUCTS_WIDTH DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
PRODUCTS_HEIGHT DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
ASIN VARCHAR(256) DEFAULT NULL,
UPC VARCHAR(256) DEFAULT NULL,
SKU VARCHAR(256) DEFAULT NULL,
EAN VARCHAR(256) DEFAULT NULL,
ISBN VARCHAR(256) DEFAULT NULL,
PRODUCTS_IMAGE_LARGE VARCHAR(64) DEFAULT NULL,
PRODUCTS_IMAGE_CROP TINYINT(1) DEFAULT '0',
PRIMARY KEY (PRODUCTS_ID),
PRODUCTS_EXTERNAL_DL VARCHAR(120) NULL,
PRODUCTS_IMAGE_1 VARCHAR(64) DEFAULT NULL,
PRODUCTS_IMAGE_2 VARCHAR(64) DEFAULT NULL,
PRODUCTS_IMAGE_3 VARCHAR(64) DEFAULT NULL,
PRODUCTS_IMAGE_4 VARCHAR(64) DEFAULT NULL,
PRODUCT_REVIEW_AVG DECIMAL(5,1) NULL,
PRODUCT_REVIEW_COUNT INT(10) DEFAULT 0,
KEY IDX_PRODUCTS_DATE_ADDED_SM (PRODUCTS_DATE_ADDED),
KEY IDX_PRODUCTS_STATUS_SM (PRODUCTS_STATUS),
KEY IDX_PRODUCTS_DATE_AVAILABLE_SM (PRODUCTS_DATE_AVAILABLE),
KEY IDX_PRODUCTS_ORDERED_SM (PRODUCTS_ORDERED),
KEY IDX_PRODUCTS_MODEL_SM (PRODUCTS_MODEL),
KEY IDX_PRODUCTS_FEATURED_SM (PRODUCTS_FEATURED),
KEY IDX_MASTER_CATEGORIES_ID_SM (MASTER_CATEGORIES_ID),
KEY IDX_PRODUCTS_SORT_ORDER_SM (PRODUCTS_SORT_ORDER),
KEY IDX_MANUFACTURERS_ID_SM (MANUFACTURERS_ID),
KEY IDX_MERCHANT_PRODUCTS_SM (MERCHANTID),
KEY IDX_PRODUCTS_TAXCLASS_SM (PRODUCTS_TAX_CLASS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


--
-- TABLE STRUCTURE FOR TABLE 'PRODUCT_RELATIONSHIP'
--

CREATE TABLE PRODUCT_RELATIONSHIP (
RELATIONSHIP_ID INT(11) NOT NULL,
MERCHANT_ID INT(11) NOT NULL,
PRODUCT_ID INT(11) NOT NULL,
RELATED_PRODUCT_ID INT(11) NOT NULL,
RELATIONSHIP_TYPE INT(3) NOT NULL DEFAULT '1',
RELATIONSHIP_ACTIVE TINYINT(1) DEFAULT '1',
PRIMARY KEY (RELATIONSHIP_ID),
KEY IDX_RELATIONSHIP_PRODUCT (MERCHANT_ID,PRODUCT_ID),
KEY IDX_RELATIONSHIP_TYPE (MERCHANT_ID,RELATIONSHIP_TYPE),
KEY IDX_RELATIONSHIP_LINE (PRODUCT_ID,RELATED_PRODUCT_ID,MERCHANT_ID,RELATIONSHIP_TYPE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;




--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS_ATTRIBUTES'
--

CREATE TABLE PRODUCTS_ATTRIBUTES (
PRODUCTS_ATTRIBUTES_ID INT(11) NOT NULL,
PRODUCTS_ID INT(11) NOT NULL DEFAULT '0',
OPTIONS_ID INT(11) NOT NULL DEFAULT '0',
OPTIONS_VALUES_ID INT(11) NOT NULL DEFAULT '0',
OPTIONS_VALUES_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
PRODUCTS_OPTIONS_SORT_ORDER INT(11) NOT NULL DEFAULT '0',
PRODUCT_ATTRIBUTE_IS_FREE TINYINT(1) DEFAULT '0',
PRODUCTS_ATTRIBUTES_WEIGHT DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
ATTRIBUTES_DEFAULT TINYINT(1) DEFAULT '0',
ATTRIBUTES_DISPLAY_ONLY TINYINT(1) DEFAULT '0',
ATTRIBUTES_DISCOUNTED TINYINT(1) DEFAULT '0',
ATTRIBUTES_REQUIRED TINYINT(1) DEFAULT '0',
PRIMARY KEY (PRODUCTS_ATTRIBUTES_ID),
KEY IDX_ID_OPTIONS_ID_VALUES_SM (PRODUCTS_ID,OPTIONS_ID,OPTIONS_VALUES_ID),
KEY IDX_PRD_ID_ATTRS_SM (PRODUCTS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS_ATTRIBUTES_DOWNLOAD'
--

CREATE TABLE PRODUCTS_ATTRIBUTES_DOWNLOAD (
PRODUCTS_ATTRIBUTES_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_ATTRIBUTES_FILENAME VARCHAR(255) CHARACTER SET UTF8 NOT NULL DEFAULT '',
PRODUCTS_ATTRIBUTES_MAXDAYS INT(2) DEFAULT '0',
PRODUCTS_ATTRIBUTES_MAXCOUNT INT(2) DEFAULT '0',
PRIMARY KEY (PRODUCTS_ATTRIBUTES_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS_DESCRIPTION'
--

CREATE TABLE PRODUCTS_DESCRIPTION (
PRODUCTS_ID INT(11) NOT NULL,
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
PRODUCTS_NAME VARCHAR(255) CHARACTER SET UTF8 DEFAULT NULL,
PRODUCTS_DESCRIPTION TEXT CHARACTER SET UTF8,
PRODUCTS_URL VARCHAR(255) DEFAULT NULL,
PRODUCTS_VIEWED INT(5) DEFAULT '0',
PRODUCTS_HIGHLIGHT VARCHAR(255) DEFAULT NULL,
SE_URL_SRC VARCHAR(100) NULL,
SE_URL VARCHAR(100) NULL,
METATAG_TITLE VARCHAR(255) DEFAULT '' NULL,
METATAG_KEYWORDS TEXT COLLATE LATIN1_GENERAL_CI NULL,
METATAG_DESCRIPTION TEXT COLLATE LATIN1_GENERAL_CI NULL,
PRODUCTS_EXTERNAL_DL VARCHAR(120) NULL,
PRODUCTS_TITLE VARCHAR(120) NULL,
PRIMARY KEY (PRODUCTS_ID,LANGUAGE_ID),
KEY IDX_PRODUCTS_NAME_SM (PRODUCTS_NAME),
KEY IDX_PRD_ID_DESC_SM (PRODUCTS_ID),
KEY IDX_PRODUCTS_SE_SM (SE_URL)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS_NOTIFICATIONS'
--

CREATE TABLE PRODUCTS_NOTIFICATIONS (
PRODUCTS_ID INT(11) NOT NULL DEFAULT '0',
CUSTOMERS_ID INT(11) NOT NULL DEFAULT '0',
DATE_ADDED DATETIME  DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (PRODUCTS_ID,CUSTOMERS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS_OPTIONS'
--

CREATE TABLE PRODUCTS_OPTIONS (
PRODUCTS_OPTIONS_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS_SORT_ORDER INT(11) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS_TYPE INT(5) NOT NULL DEFAULT '0',
MERCHANTID INT(11) DEFAULT '0',
PRIMARY KEY (PRODUCTS_OPTIONS_ID),
KEY IDX_MID_SM_OPTIONS (MERCHANTID),
KEY IDX_PRDOPT_SORT_ORDER_SM (PRODUCTS_OPTIONS_SORT_ORDER)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;




CREATE TABLE PRODUCTS_OPTIONS_DESCRIPTION (
PRODUCTS_OPTIONS_ID INT(11) NOT NULL DEFAULT '0',
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
PRODUCTS_OPTIONS_NAME VARCHAR(32) CHARACTER SET UTF8 NOT NULL DEFAULT '',
PRODUCTS_OPTIONS_COMMENT VARCHAR(64) CHARACTER SET UTF8 DEFAULT NULL,
PRIMARY KEY (PRODUCTS_OPTIONS_ID,LANGUAGE_ID),
KEY IDX_PRD_OPT_DESC_ID_SM (PRODUCTS_OPTIONS_ID),
KEY IDX_PRODUCTS_OPTIONS_NAME_SM (PRODUCTS_OPTIONS_NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS_OPTIONS_TYPES'
--

CREATE TABLE PRODUCTS_OPTIONS_TYPES (
PRODUCTS_OPTIONS_TYPES_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS_TYPES_NAME VARCHAR(32) DEFAULT NULL,
PRIMARY KEY (PRODUCTS_OPTIONS_TYPES_ID)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1 COLLATE=LATIN1_GENERAL_CI COMMENT='TRACK PRODUCTS_OPTIONS_TYPES';


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS_OPTIONS_VALUES'
--

CREATE TABLE PRODUCTS_OPTIONS_VALUES (
PRODUCTS_OPTIONS_VALUES_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS_VALUES_SORT_O INT(11) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS_VALUES_IMAGE VARCHAR(64) DEFAULT NULL,
MERCHANTID INT(11) DEFAULT '0',
PRIMARY KEY (PRODUCTS_OPTIONS_VALUES_ID),
KEY IDX_MID_SM_OPTVAL (MERCHANTID),
KEY IDX_PRD_OPT_VAL_S_ORDER_SM (PRODUCTS_OPTIONS_VALUES_SORT_O)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;




CREATE TABLE PRODUCTS_OPTIONS_VALUES_DESC (
PRODUCTS_OPTIONS_VALUES_ID INT(11) NOT NULL DEFAULT '0',
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
PRODUCTS_OPTIONS_VALUES_NAME VARCHAR(64) NOT NULL DEFAULT '',
PRIMARY KEY (PRODUCTS_OPTIONS_VALUES_ID,LANGUAGE_ID),
KEY IDX_PRD_OPT_VALUES_NAME_SM (PRODUCTS_OPTIONS_VALUES_NAME),
KEY IDX_PRD_OPT_VALUES_ID_SM (PRODUCTS_OPTIONS_VALUES_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS_OPTIONS_VAL_PRD_OPTS'
--

CREATE TABLE PRODUCTS_OPTIONS_VAL_PRD_OPTS (
PRODUCTS_OPTIONS_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_OPTIONS_VALUES_ID INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (PRODUCTS_OPTIONS_ID,PRODUCTS_OPTIONS_VALUES_ID),
KEY IDX_PRD_OPTID_SM (PRODUCTS_OPTIONS_ID),
KEY IDX_PRD_OPTIONS_VAL_ID_SM (PRODUCTS_OPTIONS_VALUES_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



--
-- TABLE STRUCTURE FOR TABLE 'PRODUCTS_TO_CATEGORIES'
--

CREATE TABLE PRODUCTS_TO_CATEGORIES (
PRODUCTS_ID INT(11) NOT NULL DEFAULT '0',
CATEGORIES_ID INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (PRODUCTS_ID,CATEGORIES_ID),
KEY IDX_CAT_PROD_ID_SM (CATEGORIES_ID,PRODUCTS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'PRODUCT_TYPES'
--

CREATE TABLE PRODUCT_TYPES (
TYPE_ID INT(11) NOT NULL AUTO_INCREMENT,
TYPE_NAME VARCHAR(255) NOT NULL DEFAULT '',
TYPE_HANDLER VARCHAR(255) NOT NULL DEFAULT '',
TYPE_MASTER_TYPE INT(11) NOT NULL DEFAULT '1',
ALLOW_ADD_TO_CART CHAR(1) NOT NULL DEFAULT 'Y',
DEFAULT_IMAGE VARCHAR(255) DEFAULT '',
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
LAST_MODIFIED DATETIME DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (TYPE_ID),
KEY IDX_TYPE_MASTER_TYPE_SM (TYPE_MASTER_TYPE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'REVIEWS'
--

CREATE TABLE REVIEWS (
REVIEWS_ID INT(11) NOT NULL,
PRODUCTS_ID INT(11) NOT NULL DEFAULT '0',
CUSTOMERS_ID INT(11) DEFAULT NULL,
CUSTOMERS_NAME VARCHAR(64) NOT NULL DEFAULT '',
REVIEWS_RATING INT(1) DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT NULL,
LAST_MODIFIED DATETIME DEFAULT NULL,
REVIEWS_READ INT(5) DEFAULT '0',
STATUS INT(1) DEFAULT '1',
PRIMARY KEY (REVIEWS_ID),
KEY IDX_PRD_ID_REV_SM (PRODUCTS_ID),
KEY IDX_CUST_ID_REV_SM (CUSTOMERS_ID),
KEY IDX_STATUS_REV_SM (STATUS),
KEY IDX_DATE_ADDED_SM (DATE_ADDED)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'REVIEWS_DESCRIPTION'
--

CREATE TABLE REVIEWS_DESCRIPTION (
REVIEWS_ID INT(11) NOT NULL DEFAULT '0',
LANGUAGES_ID INT(11) NOT NULL DEFAULT '0',
REVIEWS_TEXT TEXT CHARACTER SET UTF8 NOT NULL,
PRIMARY KEY (REVIEWS_ID,LANGUAGES_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'EVENT_TYPE'
--

CREATE TABLE EVENT_TYPE (
EVENT_TYPE_ID INT(11) NOT NULL DEFAULT '0',
EVENT_TYPE_MODULE VARCHAR(60) DEFAULT '',
EVENT_APPLY_TO_ALL_USERS TINYINT(1) DEFAULT '1',
EVENT_HAS_NOTIFICATION TINYINT(1) DEFAULT '0',
PRIMARY KEY (EVENT_TYPE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'EVENT_TYPE_ENTITY_TYPE'
--

CREATE TABLE EVENT_TYPE_ENTITY_TYPE (
EVENT_TYPE_ID INT(11) NOT NULL DEFAULT '0',
ENTITY_TYPE VARCHAR(60) NOT NULL DEFAULT '',
PRIMARY KEY (EVENT_TYPE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'EVENT'
--

CREATE TABLE EVENT (
EVENT_ID INT(11) NOT NULL DEFAULT '0',
EVENT_TYPE_ID INT(11) NOT NULL DEFAULT '0',
MERCHANT_ID INT(11) NOT NULL DEFAULT '0',
PRIMARY KEY (EVENT_ID),
KEY IDX_EVENT_TYPE (EVENT_TYPE_ID),
KEY IDX_EVENT_MERCHANT (MERCHANT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'EVENT_NOTIFICATION'
--

CREATE TABLE EVENT_NOTIFICATION (
EVENT_NOTIFICATION_ID INT(11) NOT NULL DEFAULT '0',
EVENT_ID INT(11) NOT NULL DEFAULT '0',
EVENT_NAME VARCHAR(255) NOT NULL DEFAULT '',
EVENT_TITLE VARCHAR(255) CHARACTER SET UTF8 NOT NULL DEFAULT '',
EVENT_TEXT TEXT CHARACTER SET UTF8 NOT NULL DEFAULT '',
EVENT_NOTIF_SCHEDULE_DAY INT(2) NULL,
EVENT_NOTIF_SCHEDULE_TIME INT(2) NULL ,
EVENT_NOTIF_FREQUENCE VARCHAR(20) NULL ,
EVENT_NOTIF_DATE DATETIME DEFAULT NULL,
EVENT_NOTIF_DATE_TIME INT(2) NULL ,
EVENT_NOTIF_SUBSC_ADDDAYS VARCHAR(3) NULL ,
PRIMARY KEY (EVENT_NOTIFICATION_ID),
KEY IDX_EVENT_NOTIF (EVENT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'EVENT_ENTITY_TRIGGER'
--

CREATE TABLE EVENT_ENTITY_TRIGGER (
EVENT_ENTITY_TRIGGER_ID INT(11) NOT NULL DEFAULT '0',
EVENT_ID INT(11) NOT NULL DEFAULT '0',
ENTITY_ID INT(11) NOT NULL DEFAULT '0',
EVENT_TYPE VARCHAR(60) NOT NULL DEFAULT '',
PRIMARY KEY (EVENT_ENTITY_TRIGGER_ID),
KEY IDX_EVENT_TRIGGER (EVENT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'EVENT_SUBSCRIBTION'
--

CREATE TABLE EVENT_SUBSCRIBTION (
EVENT_SUBSCRIBTION_ID INT(11) NOT NULL DEFAULT '0',
EVENT_ID INT(11) NOT NULL DEFAULT '0',
CUSTOMER_ID INT(11) NOT NULL DEFAULT '0',
OPTIN_FLAG TINYINT(1) DEFAULT '0',
PRIMARY KEY (EVENT_SUBSCRIBTION_ID),
KEY IDX_EVENT_SUBSCR (EVENT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'SPECIALS'
--

CREATE TABLE SPECIALS (
SPECIAL_ID INT(11) NOT NULL DEFAULT '0',
PRODUCTS_ID INT(11) NOT NULL DEFAULT '0',
SPECIALS_NEW_PRODUCTS_PRICE DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
SPECIALS_DATE_ADDED DATETIME DEFAULT NULL,
SPECIALS_LAST_MODIFIED DATETIME DEFAULT NULL,
EXPIRES_DATE DATE DEFAULT '0001-01-01',
DATE_STATUS_CHANGE DATETIME DEFAULT NULL,
STATUS INT(1) DEFAULT '1',
SPECIALS_DATE_AVAILABLE DATE DEFAULT '0001-01-01',
PRIMARY KEY (SPECIAL_ID),
KEY IDX_SPECIAL_PRODUCT_SM (PRODUCTS_ID),
KEY IDX_STATUS_SPEC_SM (STATUS),
KEY IDX_DATE_AVAIL_SM (SPECIALS_DATE_AVAILABLE),
KEY IDX_EXPIRES_DATE_SM (EXPIRES_DATE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

CREATE TABLE PRODUCTS_PRICE (
PRODUCT_PRICE_ID INT(11) NOT NULL,
PRODUCT_ID INT(11) NOT NULL,
PRODUCT_PRICE_TYPE_ID INT(3) NOT NULL DEFAULT '0',
PRODUCT_PRICE_MODULE_NAME VARCHAR(64) NOT NULL,
PRODUCT_PRICE_AMOUNT DECIMAL(15,2) NOT NULL,
DEFAULT_PRICE TINYINT(1) DEFAULT '1',
PRIMARY KEY (PRODUCT_PRICE_ID),
KEY SM_IDX_PRD_PRICE_PRD_ID (PRODUCT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;




CREATE TABLE PRODUCTS_PRICE_DESCRIPTION (
PRODUCT_PRICE_ID INT(11) NOT NULL,
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
PRODUCT_PRICE_NAME VARCHAR(255) CHARACTER SET UTF8 DEFAULT NULL,
PRIMARY KEY (PRODUCT_PRICE_ID,LANGUAGE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



CREATE TABLE PRODUCTS_PRICE_SPECIALS (
PRODUCT_PRICE_ID INT(11) NOT NULL,
PRODUCT_PRICE_SPECIAL_ST_DATE DATETIME NULL,
PRODUCT_PRICE_SPECIAL_END_DATE DATETIME NULL,
PRODUCT_PRICE_SPECIAL_DAYS INT(3) NULL, 
PRODUCT_PRICE_SPECIAL_AMOUNT DECIMAL(15,2) NOT NULL, 
PRIMARY KEY (PRODUCT_PRICE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


CREATE TABLE ORDERS_ACCOUNT (
ORDER_ACCOUNT_ID INT(11) NOT NULL,
ORDER_ID INT(11) NOT NULL,
ORDER_ACCOUNT_STATUS_ID INT(5) NOT NULL,
ORDER_ACCOUNT_START_DATE DATETIME NOT NULL,
ORDER_ACCOUNT_END_DATE DATETIME NULL,
ORDER_ACCOUNT_BILL_DAY INT(2) NOT NULL DEFAULT 0, 
PRIMARY KEY (ORDER_ACCOUNT_ID),
KEY SM_IDX_ORDER_ID (ORDER_ID),
KEY SM_IDX_ORDER_ACCOUNT_STATUS (ORDER_ACCOUNT_STATUS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

CREATE TABLE ORDERS_ACCOUNT_STATUS_HISTORY (
ORDER_ACCNT_STAT_HISTORY_ID INT(11) NOT NULL,
ORDER_ACCOUNT_ID INT(11) NOT NULL,
ORDER_ACCNT_STAT_ID INT(5) NOT NULL DEFAULT '0',
ORDER_ACCNT_STAT_HISTORY_NAME VARCHAR(32) NOT NULL,
DATE_ADDED DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
CUSTOMER_NOTIFIED INT(1) DEFAULT '0',
COMMENTS TEXT COLLATE UTF8_UNICODE_CI,
PRIMARY KEY (ORDER_ACCNT_STAT_HISTORY_ID),
KEY SM_IDX_ORDER_ACCOUNT_ID (ORDER_ACCOUNT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



CREATE TABLE ORDERS_ACCNT_TRX_HISTORY (
ORDER_ACCNT_TRX_HISTORY_ID INT(11) NOT NULL,
ORDER_ACCOUNT_ID INT(11) NOT NULL,
ORDER_ACCNT_TRX_DATE DATETIME NOT NULL,
ORDER_ACCNT_TRX_AMOUNT DECIMAL(15,2) NOT NULL,
ORDER_ACCNT_TRX_STATUS INT(11) NOT NULL,
ORDER_ACCNT_TRX_STATUS_TEXT VARCHAR(255) NOT NULL, 
PRIMARY KEY (ORDER_ACCNT_TRX_HISTORY_ID),
KEY SM_IDX_ORDER_ACCNT_TRX_ID (ORDER_ACCOUNT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


CREATE TABLE ORDERS_ACCOUNT_PRODUCTS (
ORDER_ACCOUNT_PRODUCT_ID INT(11) NOT NULL,
ORDER_ACCOUNT_ID INT(11) NOT NULL,
ORDER_PRODUCT_ID INT(11) NOT NULL DEFAULT '0',
ORDER_ACCOUNT_PRODUCT_ST_DT DATETIME NOT NULL,
ORDER_ACCOUNT_PRODUCT_END_DT DATETIME NULL,
ORDER_ACCOUNT_PRODUCT_EOT DATETIME NULL,
ORDER_ACCOUNT_PRODUCT_ACCNT_DT DATETIME NULL, 
ORDER_ACCOUNT_PRODUCT_L_ST_DT DATETIME NULL,
ORDER_ACCOUNT_PRODUCT_L_TRX_ST INT(3) NOT NULL DEFAULT '-1',
ORDER_ACCOUNT_PRODUCT_PM_FR_TY INT(2) NOT NULL DEFAULT '1',
ORDER_ACCOUNT_PRODUCT_STATUS INT(3) NOT NULL DEFAULT '0', 
PRIMARY KEY (ORDER_ACCOUNT_PRODUCT_ID),
KEY IDX_ORDER_ACCOUNT_ID_SM (ORDER_ACCOUNT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------
--
-- PORTLET
--

CREATE TABLE PORTLET (
PORTLET_ID INT(11) NOT NULL,
MERCHANT_ID INT(11) NOT NULL,
PAGE INT(11) NOT NULL,
TITLE VARCHAR(60) NOT NULL,
NAME VARCHAR(100) NULL,
PORTLET_TYPE INT(3) DEFAULT 0,
LABEL_ID INT(11) NOT NULL,
VISIBLE TINYINT(1) DEFAULT '0',
ENABLED TINYINT(1) DEFAULT '1',  
SORT_ORDER INT(3) DEFAULT 0,
COLUMN_ID VARCHAR(20) NOT NULL, 
PRIMARY KEY (PORTLET_ID),
KEY IDX_PORTLET_MERCHANT_ID_SM (MERCHANT_ID),
KEY IDX_PORTLET_PAGE_ID_SM (MERCHANT_ID, PAGE),
KEY IDX_PORTLET_PG_COL_ID_SM (MERCHANT_ID, PAGE, COLUMN_ID),
KEY IDX_PORTLET_LABEL_ID_SM (MERCHANT_ID, LABEL_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------
--
-- PAGE
--

CREATE TABLE PAGE (
	PAGE_ID INT(11) NOT NULL,
	MERCHANT_ID INT(11) NOT NULL,
	HEADER TEXT CHARACTER SET UTF8,
	TITLE VARCHAR(60) NOT NULL,
	NAME VARCHAR(100) NULL,
	VISIBLE TINYINT(1) DEFAULT '0',
	ENABLED TINYINT(1) DEFAULT '1',
      SECURED TINYINT(1) DEFAULT '0',
	STYLE INT(4) NOT NULL,
	PROPERTY1 VARCHAR(120) NULL,
	PROPERTY2 VARCHAR(120) NULL,
	PROPERTY3 VARCHAR(120) NULL,   
	PROPERTY4 VARCHAR(120) NULL, 
	PROPERTY5 VARCHAR(120) NULL,
      PROPERTY6 VARCHAR(120) NULL,
      PROPERTY7 VARCHAR(120) NULL,
      PROPERTY8 VARCHAR(120) NULL,
      PROPERTY9 VARCHAR(120) NULL,
      PROPERTY10 VARCHAR(120) NULL, 
	PRIMARY KEY (PAGE_ID),
        KEY IDX_PAGE_MERCHANT_ID_SM (MERCHANT_ID),
	KEY IDX_TITLE_MERCHANT_ID_SM (MERCHANT_ID,TITLE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------
--
-- DYNAMIC LABEL
--

CREATE TABLE DYNAMIC_LABEL (
DYNAMIC_LABEL_ID INT(11) NOT NULL,
MERCHANT_ID INT(11) NOT NULL,
TITLE VARCHAR(60) NULL,
IMAGE VARCHAR(60) NULL,
SECTION_ID INT(11) NOT NULL,
VISIBLE TINYINT(1) DEFAULT '1', 
SORT_ORDER INT(3) DEFAULT 0,
POSITION INT(2) DEFAULT 0, 
PRIMARY KEY (DYNAMIC_LABEL_ID),
KEY IDX_DYNAMIC_LABEL_ID_SM (MERCHANT_ID,SECTION_ID),
KEY IDX_DYNAMIC_LABEL_TL_SM (MERCHANT_ID,TITLE),
KEY IDX_DYNAMIC_LABEL_ST_SM (MERCHANT_ID,SECTION_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;




CREATE TABLE DYNAMIC_LABEL_DESCRIPTION (
DYNAMIC_LABEL_ID INT(11) NOT NULL,
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
DYNAMIC_LABEL_TITLE VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
SE_URL VARCHAR(100) NULL,
DYNAMIC_LABEL_DESCRIPTION TEXT CHARACTER SET UTF8,
PRIMARY KEY (DYNAMIC_LABEL_ID,LANGUAGE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;



-- --------------------------------------------------------
--
-- TABLE STRUCTURE FOR TABLE 'TAX_CLASS'
--

CREATE TABLE TAX_CLASS (
TAX_CLASS_ID INT(11) NOT NULL,
TAX_CLASS_TITLE VARCHAR(32) NOT NULL DEFAULT '',
TAX_CLASS_DESCRIPTION VARCHAR(255) CHARACTER SET UTF8 NOT NULL DEFAULT '',
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_ADDED DATETIME DEFAULT '0001-01-01 00:00:00',
MERCHANTID INT(11) DEFAULT '0',
PRIMARY KEY (TAX_CLASS_ID),
KEY IDX_MERCHANT_TAX_CLASS (MERCHANTID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'TAX_RATES_TAX_TEMPLATE'
--

CREATE TABLE TAX_RATES_TAX_TEMPLATE (
TAX_RATES_ID INT(11) NOT NULL AUTO_INCREMENT,
TAX_ZONE_ID INT(11) NOT NULL DEFAULT '0',
TAX_CLASS_ID INT(11) NOT NULL DEFAULT '0',
TAX_PRIORITY INT(5) DEFAULT '1',
TAX_RATE DECIMAL(7,4) NOT NULL DEFAULT '0.0000',
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_ADDED DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
PIGGYBACK TINYINT(1) DEFAULT '0',
PRIMARY KEY (TAX_RATES_ID),
KEY IDX_MERCH_TAX_ZNID_TPL_SM (TAX_ZONE_ID),
KEY IDX_MERCH_TX_CLS_IDTPL_SM (TAX_CLASS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

CREATE TABLE TAX_RATES_DESCRIPTION_TAX_TPL (
TAX_RATES_ID INT(11) NOT NULL,
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
TAX_DESCRIPTION VARCHAR(255) CHARACTER SET UTF8 NOT NULL DEFAULT '',
PRIMARY KEY (TAX_RATES_ID,LANGUAGE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;




-- --------------------------------------------------------


--
-- TABLE STRUCTURE FOR TABLE 'ZONES'
--

CREATE TABLE ZONES (
ZONE_ID INT(11) NOT NULL AUTO_INCREMENT,
ZONE_COUNTRY_ID INT(11) NOT NULL DEFAULT '0',
ZONE_CODE VARCHAR(32) NOT NULL DEFAULT '',
PRIMARY KEY (ZONE_ID),
KEY IDX_ZONE_COUNTRY_ID_SM (ZONE_COUNTRY_ID),
KEY IDX_ZONE_CODE_SM (ZONE_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


CREATE TABLE ZONES_DESCRIPTION (
ZONE_ID INT(11) NOT NULL,
LANGUAGE_ID INT(11) NOT NULL DEFAULT '1',
ZONE_NAME VARCHAR(32) NOT NULL DEFAULT '',
PRIMARY KEY (ZONE_ID,LANGUAGE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;


-- --------------------------------------------------------

--
-- TABLE STRUCTURE FOR TABLE 'ZONES_TO_GEO_ZONES_TAX_TPL'
--

CREATE TABLE ZONES_TO_GEO_ZONES_TAX_TPL (
ASSOCIATION_ID INT(11) NOT NULL,
ZONE_COUNTRY_ID INT(11) NOT NULL DEFAULT '0',
ZONE_ID INT(11) DEFAULT NULL,
GEO_ZONE_ID INT(11) DEFAULT NULL,
LAST_MODIFIED DATETIME DEFAULT NULL,
DATE_ADDED DATETIME NOT NULL DEFAULT '0001-01-01 00:00:00',
PRIMARY KEY (ASSOCIATION_ID),
KEY IDX_ZONES_SM (GEO_ZONE_ID,ZONE_COUNTRY_ID,ZONE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE=UTF8_UNICODE_CI;

