/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.reference;

// Generated May 25, 2009 12:08:19 PM by Hibernate Tools 3.2.0.beta8

/**
 * DynamicLabelDescription generated by hbm2java
 */
public class DynamicLabelDescription implements java.io.Serializable {

	// Fields

	private DynamicLabelDescriptionId id;
	private String dynamicLabelDescription;

	private DynamicLabel dynamicLabel;
	private String dynamicLabelTitle;
	private String seUrl;

	// Constructors

	/** default constructor */
	public DynamicLabelDescription() {
	}

	/** minimal constructor */
	public DynamicLabelDescription(DynamicLabelDescriptionId id) {
		this.id = id;
	}

	/** full constructor */
	public DynamicLabelDescription(DynamicLabelDescriptionId id,
			String dynamicLabelDescription) {
		this.id = id;
		this.dynamicLabelDescription = dynamicLabelDescription;
	}

	// Property accessors
	public DynamicLabelDescriptionId getId() {
		return this.id;
	}

	public void setId(DynamicLabelDescriptionId id) {
		this.id = id;
	}

	public String getDynamicLabelDescription() {
		return this.dynamicLabelDescription;
	}

	public void setDynamicLabelDescription(String dynamicLabelDescription) {
		this.dynamicLabelDescription = dynamicLabelDescription;
	}

	public DynamicLabel getDynamicLabel() {
		return dynamicLabel;
	}

	public void setDynamicLabel(DynamicLabel dynamicLabel) {
		this.dynamicLabel = dynamicLabel;
	}

	public String getDynamicLabelTitle() {
		return dynamicLabelTitle;
	}

	public void setDynamicLabelTitle(String dynamicLabelTitle) {
		this.dynamicLabelTitle = dynamicLabelTitle;
	}

	public String getSeUrl() {
		return seUrl;
	}

	public void setSeUrl(String seUrl) {
		this.seUrl = seUrl;
	}

}
