/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.reference;

// Generated Nov 11, 2009 9:19:10 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Manufacturers generated by hbm2java
 */
public class Manufacturers implements java.io.Serializable {

	private Integer manufacturersId;
	private String manufacturersName;
	private String manufacturersImage;
	private Date dateAdded;
	private Date lastModified;

	public Manufacturers() {
	}

	public Manufacturers(String manufacturersName) {
		this.manufacturersName = manufacturersName;
	}

	public Manufacturers(String manufacturersName, String manufacturersImage,
			Date dateAdded, Date lastModified) {
		this.manufacturersName = manufacturersName;
		this.manufacturersImage = manufacturersImage;
		this.dateAdded = dateAdded;
		this.lastModified = lastModified;
	}

	public Integer getManufacturersId() {
		return this.manufacturersId;
	}

	public void setManufacturersId(Integer manufacturersId) {
		this.manufacturersId = manufacturersId;
	}

	public String getManufacturersName() {
		return this.manufacturersName;
	}

	public void setManufacturersName(String manufacturersName) {
		this.manufacturersName = manufacturersName;
	}

	public String getManufacturersImage() {
		return this.manufacturersImage;
	}

	public void setManufacturersImage(String manufacturersImage) {
		this.manufacturersImage = manufacturersImage;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}
