/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.reference;

// Generated Nov 11, 2009 9:19:10 AM by Hibernate Tools 3.2.4.GA

/**
 * ManufacturersInfoId generated by hbm2java
 */
public class ManufacturersInfoId implements java.io.Serializable {

	private int manufacturersId;
	private int languagesId;

	public ManufacturersInfoId() {
	}

	public ManufacturersInfoId(int manufacturersId, int languagesId) {
		this.manufacturersId = manufacturersId;
		this.languagesId = languagesId;
	}

	public int getManufacturersId() {
		return this.manufacturersId;
	}

	public void setManufacturersId(int manufacturersId) {
		this.manufacturersId = manufacturersId;
	}

	public int getLanguagesId() {
		return this.languagesId;
	}

	public void setLanguagesId(int languagesId) {
		this.languagesId = languagesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ManufacturersInfoId))
			return false;
		ManufacturersInfoId castOther = (ManufacturersInfoId) other;

		return (this.getManufacturersId() == castOther.getManufacturersId())
				&& (this.getLanguagesId() == castOther.getLanguagesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getManufacturersId();
		result = 37 * result + this.getLanguagesId();
		return result;
	}

}
