/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.reference;

import java.util.List;

// Generated Jul 11, 2008 8:33:48 AM by Hibernate Tools 3.2.0.b9

/**
 * ModuleConfiguration generated by hbm2java
 */
public class ModuleConfiguration implements java.io.Serializable {

	private ModuleConfigurationId id;

	private String configurationValue;

	private List<String> parsedConfigurationValue;

	public ModuleConfiguration() {
	}

	public ModuleConfiguration(ModuleConfigurationId id) {
		this.id = id;
	}

	public ModuleConfiguration(ModuleConfigurationId id,
			String configurationValue) {
		this.id = id;
		this.configurationValue = configurationValue;
	}

	public ModuleConfigurationId getId() {
		return this.id;
	}

	public void setId(ModuleConfigurationId id) {
		this.id = id;
	}

	public String getConfigurationValue() {
		return this.configurationValue;
	}

	public void setConfigurationValue(String configurationValue) {
		this.configurationValue = configurationValue;
	}

	public List<String> getParsedConfigurationValue() {
		return parsedConfigurationValue;
	}

	public void setParsedConfigurationValue(
			List<String> parsedConfigurationValue) {
		this.parsedConfigurationValue = parsedConfigurationValue;
	}

}
