/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.reference;

// Generated Jul 11, 2008 8:33:48 AM by Hibernate Tools 3.2.0.b9

/**
 * ModuleConfigurationId generated by hbm2java
 */
public class ModuleConfigurationId implements java.io.Serializable {

	private String configurationModule;

	private String configurationKey;

	private String countryIsoCode2;

	public ModuleConfigurationId() {
	}

	public ModuleConfigurationId(String configurationModule,
			String configurationKey, String countryIsoCode2) {
		this.configurationModule = configurationModule;
		this.configurationKey = configurationKey;
		this.countryIsoCode2 = countryIsoCode2;
	}

	public String getConfigurationModule() {
		return this.configurationModule;
	}

	public void setConfigurationModule(String configurationModule) {
		this.configurationModule = configurationModule;
	}

	public String getConfigurationKey() {
		return this.configurationKey;
	}

	public void setConfigurationKey(String configurationKey) {
		this.configurationKey = configurationKey;
	}

	public String getCountryIsoCode2() {
		return this.countryIsoCode2;
	}

	public void setCountryIsoCode2(String countryIsoCode2) {
		this.countryIsoCode2 = countryIsoCode2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModuleConfigurationId))
			return false;
		ModuleConfigurationId castOther = (ModuleConfigurationId) other;

		return ((this.getConfigurationModule() == castOther
				.getConfigurationModule()) || (this.getConfigurationModule() != null
				&& castOther.getConfigurationModule() != null && this
				.getConfigurationModule().equals(
						castOther.getConfigurationModule())))
				&& ((this.getConfigurationKey() == castOther
						.getConfigurationKey()) || (this.getConfigurationKey() != null
						&& castOther.getConfigurationKey() != null && this
						.getConfigurationKey().equals(
								castOther.getConfigurationKey())))
				&& ((this.getCountryIsoCode2() == castOther
						.getCountryIsoCode2()) || (this.getCountryIsoCode2() != null
						&& castOther.getCountryIsoCode2() != null && this
						.getCountryIsoCode2().equals(
								castOther.getCountryIsoCode2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getConfigurationModule() == null ? 0 : this
						.getConfigurationModule().hashCode());
		result = 37
				* result
				+ (getConfigurationKey() == null ? 0 : this
						.getConfigurationKey().hashCode());
		result = 37
				* result
				+ (getCountryIsoCode2() == null ? 0 : this.getCountryIsoCode2()
						.hashCode());
		return result;
	}

}
