package com.salesmanager.core.entity.reference;
// Generated Oct 28, 2010 6:11:59 PM by Hibernate Tools 3.2.4.GA



/**
 * Page generated by hbm2java
 */
public class Page  implements java.io.Serializable {


     private long pageId;
     private int merchantId;
     private String header;
     private String title;
     private String name;
     private boolean visible;
     private boolean enabled;
     private boolean secured;
     private int style;
     private String property1;
     private String property2;
     private String property3;
     private String property4;
     private String property5;
     private String property6;
     private String property7;
     private String property8;
     private String property9;
     private String property10;

    public Page() {
    }

	
    public Page(long pageId, int merchantId, String title, int style) {
        this.pageId = pageId;
        this.merchantId = merchantId;
        this.title = title;
        this.style = style;
    }
    public Page(long pageId, int merchantId, String header, String title, String name, boolean visible, boolean enabled, int style) {
       this.pageId = pageId;
       this.merchantId = merchantId;
       this.header = header;
       this.title = title;
       this.name = name;
       this.visible = visible;
       this.enabled = enabled;
       this.style = style;
    }
   
    public long getPageId() {
        return this.pageId;
    }
    
    public void setPageId(long pageId) {
        this.pageId = pageId;
    }
    public int getMerchantId() {
        return this.merchantId;
    }
    
    public void setMerchantId(int merchantId) {
        this.merchantId = merchantId;
    }
    public String getHeader() {
        return this.header;
    }
    
    public void setHeader(String header) {
        this.header = header;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }
    public boolean getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public int getStyle() {
        return this.style;
    }
    
    public void setStyle(int style) {
        this.style = style;
    }


	public String getProperty1() {
		return property1;
	}


	public void setProperty1(String property1) {
		this.property1 = property1;
	}


	public String getProperty2() {
		return property2;
	}


	public void setProperty2(String property2) {
		this.property2 = property2;
	}


	public String getProperty3() {
		return property3;
	}


	public void setProperty3(String property3) {
		this.property3 = property3;
	}


	public String getProperty4() {
		return property4;
	}


	public void setProperty4(String property4) {
		this.property4 = property4;
	}


	public String getProperty5() {
		return property5;
	}


	public void setProperty5(String property5) {
		this.property5 = property5;
	}


	public boolean getSecured() {
		return secured;
	}


	public void setSecured(boolean secured) {
		this.secured = secured;
	}


	public String getProperty6() {
		return property6;
	}


	public void setProperty6(String property6) {
		this.property6 = property6;
	}


	public String getProperty7() {
		return property7;
	}


	public void setProperty7(String property7) {
		this.property7 = property7;
	}


	public String getProperty8() {
		return property8;
	}


	public void setProperty8(String property8) {
		this.property8 = property8;
	}


	public String getProperty9() {
		return property9;
	}


	public void setProperty9(String property9) {
		this.property9 = property9;
	}


	public String getProperty10() {
		return property10;
	}


	public void setProperty10(String property10) {
		this.property10 = property10;
	}




}


