/*
 * Licensed to csti consulting 
 * You may obtain a copy of the License at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-Aug 24, 2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.core.entity.customer;

// Generated Mar 8, 2009 10:16:39 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

import com.salesmanager.core.util.DateUtil;

/**
 * CustomersInfo generated by hbm2java
 */
public class CustomerInfo implements java.io.Serializable {

	// Fields

	private long customerInfoId;

	private Date customerInfoDateOfLastLogon;

	private Integer customerInfoNumberOfLogon;

	private Date customerInfoDateAccountCreated;

	private Date customerInfoDateAccountLastModified;

	private Integer globalProductNotifications;

	private void init() {
		customerInfoDateOfLastLogon = new Date();
		customerInfoDateAccountCreated = new Date();
		customerInfoDateAccountLastModified = new Date();
		globalProductNotifications = new Integer(0);
		customerInfoNumberOfLogon = new Integer(0);
	}

	// Constructors

	/** default constructor */
	public CustomerInfo() {
		init();
	}

	/** minimal constructor */
	public CustomerInfo(long customerInfoId) {
		this.customerInfoId = customerInfoId;
	}

	/** full constructor */
	public CustomerInfo(int customerInfoId, Date customerInfoDateOfLastLogon,
			Integer customerInfoNumberOfLogons,
			Date customerInfoDateAccountCreated,
			Date customerInfoDateAccountLastModified,
			Integer globalProductNotifications) {
		this.customerInfoId = customerInfoId;
		this.customerInfoDateOfLastLogon = customerInfoDateOfLastLogon;
		this.customerInfoNumberOfLogon = customerInfoNumberOfLogon;
		this.customerInfoDateAccountCreated = customerInfoDateAccountCreated;
		this.customerInfoDateAccountLastModified = customerInfoDateAccountLastModified;
		this.globalProductNotifications = globalProductNotifications;
	}

	// Property accessors
	public long getCustomerInfoId() {
		return this.customerInfoId;
	}

	public void setCustomerInfoId(long customerInfoId) {
		this.customerInfoId = customerInfoId;
	}

	public Date getCustomerInfoDateOfLastLogon() {
		return this.customerInfoDateOfLastLogon;
	}

	public String getCustomerInfoDateOfLastLogonText() {

		return DateUtil.formatDate(this.customerInfoDateOfLastLogon);

	}

	public void setCustomerInfoDateOfLastLogon(Date customerInfoDateOfLastLogon) {
		this.customerInfoDateOfLastLogon = customerInfoDateOfLastLogon;
	}

	public Integer getCustomerInfoNumberOfLogon() {
		return this.customerInfoNumberOfLogon;
	}

	public void setCustomerInfoNumberOfLogon(Integer customerInfoNumberOfLogon) {
		this.customerInfoNumberOfLogon = customerInfoNumberOfLogon;
	}

	public Date getCustomerInfoDateAccountCreated() {
		return this.customerInfoDateAccountCreated;
	}

	public void setCustomerInfoDateAccountCreated(
			Date customerInfoDateAccountCreated) {
		this.customerInfoDateAccountCreated = customerInfoDateAccountCreated;
	}

	public Date getCustomerInfoDateAccountLastModified() {
		return this.customerInfoDateAccountLastModified;
	}

	public String getCustomerInfoDateAccountLastModifiedText() {

		return DateUtil.formatDate(this.customerInfoDateAccountLastModified);

	}

	public void setCustomerInfoDateAccountLastModified(
			Date customerInfoDateAccountLastModified) {
		this.customerInfoDateAccountLastModified = customerInfoDateAccountLastModified;
	}

	public Integer getGlobalProductNotifications() {
		return this.globalProductNotifications;
	}

	public void setGlobalProductNotifications(Integer globalProductNotifications) {
		this.globalProductNotifications = globalProductNotifications;
	}

}
